In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from pathlib import Path

In [2]:
print("Current working directory:", os.getcwd())
try:
    os.chdir('Dataset') 
    print("Current working directory:", os.getcwd())
except:
    pass

Current working directory: /Users/qiyanjie/Desktop/Fall2022/Database/FinalProject
Current working directory: /Users/qiyanjie/Desktop/Fall2022/Database/FinalProject/Dataset

# Data Cleaning of Video_Games_Sales Data and computer game Data

In [3]:
# vgsales = pd.read_csv('vgsales.csv')
vgsales = pd.read_csv('Video_Games_Sales_as_at_22_Dec_2016.csv')

In [4]:
print(vgsales.head(10))
print(vgsales.shape)

                        Name Platform  Year_of_Release         Genre  \
0                 Wii Sports      Wii           2006.0        Sports
1          Super Mario Bros.      NES           1985.0      Platform
2             Mario Kart Wii      Wii           2008.0        Racing
3          Wii Sports Resort      Wii           2009.0        Sports
4   Pokemon Red/Pokemon Blue       GB           1996.0  Role-Playing
5                     Tetris       GB           1989.0        Puzzle
6      New Super Mario Bros.       DS           2006.0      Platform
7                   Wii Play      Wii           2006.0          Misc
8  New Super Mario Bros. Wii      Wii           2009.0      Platform
9                  Duck Hunt      NES           1984.0       Shooter

  Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  \
0  Nintendo     41.36     28.96      3.77         8.45         82.53
1  Nintendo     29.08      3.58      6.81         0.77         40.24
2  Nintendo     15.68     12.76      3.79         3.29         35.52
3  Nintendo     15.61     10.93      3.28         2.95         32.77
4  Nintendo     11.27      8.89     10.22         1.00         31.37
5  Nintendo     23.20      2.26      4.22         0.58         30.26
6  Nintendo     11.28      9.14      6.50         2.88         29.80
7  Nintendo     13.96      9.18      2.93         2.84         28.92
8  Nintendo     14.44      6.94      4.70         2.24         28.32
9  Nintendo     26.93      0.63      0.28         0.47         28.31

   Critic_Score  Critic_Count User_Score  User_Count Developer Rating
0          76.0          51.0          8       322.0  Nintendo      E
1           NaN           NaN        NaN         NaN       NaN    NaN
2          82.0          73.0        8.3       709.0  Nintendo      E
3          80.0          73.0          8       192.0  Nintendo      E
4           NaN           NaN        NaN         NaN       NaN    NaN
5           NaN           NaN        NaN         NaN       NaN    NaN
6          89.0          65.0        8.5       431.0  Nintendo      E
7          58.0          41.0        6.6       129.0  Nintendo      E
8          87.0          80.0        8.4       594.0  Nintendo      E
9           NaN           NaN        NaN         NaN       NaN    NaN
(16719, 16)

In [5]:
cg = pd.read_csv('computer_games.csv')
cg.head(10)

,Name,Developer,Producer,Genre,Operating System,Date Released
0,A-Men 2,Bloober Team,Bloober Team,"Adventure, Puzzle",Microsoft Windows,"June 24, 2015"
1,A-Train,Artdink,"Artdink, Maxis, Ocean Software",Vehicle Simulation Game,"Windows, Mac",1985
2,A-10 Cuba!,Parsoft Interactive,Activision,Flight simulator,"Windows, Mac","November 30, 1996"
3,A.D. 2044,R.M.P. Software,LK Avalon,Adventure,Microsoft Windows,"September 6, 1996"
4,A.D.A.M. Life's Greatest Mysteries,Columbia Healthcare Corporation,Columbia Healthcare Corporation,Educational,Microsoft Windows,1996
5,A.D.A.M. The Inside Story,Columbia Healthcare Corporation,Columbia Healthcare Corporation,Educational,Microsoft Windows,1995
6,A.R.E.S.: Extinction Agenda,Extend Studio,"Origo Games, Aksys Games","Action, platform",Microsoft Windows,"December 14, 2010"
7,A Girls Fabric Face,Stanislaw Truchowskit,TurnVex,Adventure,Microsoft Windows,"March 10, 2017"
8,A Hat in Time,Gears for Breakfast,Gears for Breakfast,"Platform, action-adventure","macOS, Microsoft Windows","October 5, 2017"
9,A Game of Thrones: Genesis,Cyanide,Focus Home Interactive,Strategy,Microsoft Windows,"September 28, 2011"

In [6]:
cgDict = {}
vgDict = {}

for cidx, cName in enumerate(cg.Name):
    for vidx, vName in enumerate(vgsales.Name):
        if cName == vName:
            cgDict[cName] = cidx
            vgDict[vName] = vidx

print(len(cgDict))
print(len(vgDict))

399
399

In [7]:
newGamedf = vgsales.merge(cg, on='Name')
newGamedf.isnull().any()

Name                False
Platform            False
Year_of_Release      True
Genre_x             False
Publisher            True
NA_Sales            False
EU_Sales            False
JP_Sales            False
Other_Sales         False
Global_Sales        False
Critic_Score         True
Critic_Count         True
User_Score           True
User_Count           True
Developer_x          True
Rating               True
Developer_y         False
Producer            False
Genre_y             False
Operating System    False
Date Released       False
dtype: bool

In [8]:
newGamedf = newGamedf.dropna(how='any',axis=0)
newGamedf.drop(columns=['Developer_y'])
newGamedf

,Name,Platform,Year_of_Release,Genre_x,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,...,Critic_Count,User_Score,User_Count,Developer_x,Rating,Developer_y,Producer,Genre_y,Operating System,Date Released
0,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.02,9.09,0.98,3.96,21.04,...,50.0,8.2,3994.0,Rockstar North,M,Rockstar North,Rockstar Games,"Open world, action-adventure",Microsoft Windows,"April 14, 2015"
1,Grand Theft Auto V,X360,2013.0,Action,Take-Two Interactive,9.66,5.14,0.06,1.41,16.27,...,58.0,8.1,3711.0,Rockstar North,M,Rockstar North,Rockstar Games,"Open world, action-adventure",Microsoft Windows,"April 14, 2015"
2,Grand Theft Auto V,PS4,2014.0,Action,Take-Two Interactive,3.96,6.31,0.38,1.97,12.61,...,66.0,8.3,2899.0,Rockstar North,M,Rockstar North,Rockstar Games,"Open world, action-adventure",Microsoft Windows,"April 14, 2015"
3,Grand Theft Auto V,XOne,2014.0,Action,Take-Two Interactive,2.81,2.19,0.00,0.47,5.48,...,14.0,7.9,764.0,Rockstar North,M,Rockstar North,Rockstar Games,"Open world, action-adventure",Microsoft Windows,"April 14, 2015"
4,Grand Theft Auto V,PC,2015.0,Action,Take-Two Interactive,0.39,0.69,0.00,0.09,1.17,...,57.0,7.9,3756.0,Rockstar North,M,Rockstar North,Rockstar Games,"Open world, action-adventure",Microsoft Windows,"April 14, 2015"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
917,Unreal Tournament 2003,PC,2002.0,Shooter,Atari,0.00,0.01,0.00,0.00,0.01,...,27.0,8.2,98.0,Digital Extremes,M,"Epic Games, Digital Extremes",Infogrames,First-person shooter,"Microsoft Windows, Linux, macOS","October 1, 2002"
918,Neverwinter Nights 2: Mask of the Betrayer,PC,2007.0,Role-Playing,Atari,0.00,0.01,0.00,0.00,0.01,...,25.0,8.8,182.0,Obsidian Entertainment,T,Obsidian Entertainment,Atari,RPG,"Microsoft Windows, macOS","October 9, 2007"
919,Deus Ex,PC,2000.0,Role-Playing,Eidos Interactive,0.00,0.01,0.00,0.00,0.01,...,28.0,9.3,1069.0,Ion Storm,M,Ion Storm,Eidos Interactive,Action role-playing,"Microsoft Windows, macOS","June 26, 2000"
920,Goat Simulator,XOne,2016.0,Simulation,Koch Media,0.00,0.01,0.00,0.00,0.01,...,15.0,6.3,63.0,Coffee Stain Studios,T,Coffee Stain Studios,Coffee Stain Studios,"Nonlinear, sandbox physics","Microsoft Windows, Linux, macOS","April 1, 2014"
922,Icewind Dale II,PC,2002.0,Role-Playing,Interplay,0.00,0.01,0.00,0.00,0.01,...,22.0,8.3,147.0,Black Isle Studios,T,Black Isle Studios,Interplay Entertainment,RPG,Microsoft Windows,"August 27, 2002"

In [9]:
newGamedf = newGamedf.drop(columns=['Year_of_Release','Genre_x', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Developer_y'])
newGamedf

,Name,Platform,Publisher,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer_x,Rating,Producer,Genre_y,Operating System,Date Released
0,Grand Theft Auto V,PS3,Take-Two Interactive,21.04,97.0,50.0,8.2,3994.0,Rockstar North,M,Rockstar Games,"Open world, action-adventure",Microsoft Windows,"April 14, 2015"
1,Grand Theft Auto V,X360,Take-Two Interactive,16.27,97.0,58.0,8.1,3711.0,Rockstar North,M,Rockstar Games,"Open world, action-adventure",Microsoft Windows,"April 14, 2015"
2,Grand Theft Auto V,PS4,Take-Two Interactive,12.61,97.0,66.0,8.3,2899.0,Rockstar North,M,Rockstar Games,"Open world, action-adventure",Microsoft Windows,"April 14, 2015"
3,Grand Theft Auto V,XOne,Take-Two Interactive,5.48,97.0,14.0,7.9,764.0,Rockstar North,M,Rockstar Games,"Open world, action-adventure",Microsoft Windows,"April 14, 2015"
4,Grand Theft Auto V,PC,Take-Two Interactive,1.17,96.0,57.0,7.9,3756.0,Rockstar North,M,Rockstar Games,"Open world, action-adventure",Microsoft Windows,"April 14, 2015"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
917,Unreal Tournament 2003,PC,Atari,0.01,86.0,27.0,8.2,98.0,Digital Extremes,M,Infogrames,First-person shooter,"Microsoft Windows, Linux, macOS","October 1, 2002"
918,Neverwinter Nights 2: Mask of the Betrayer,PC,Atari,0.01,82.0,25.0,8.8,182.0,Obsidian Entertainment,T,Atari,RPG,"Microsoft Windows, macOS","October 9, 2007"
919,Deus Ex,PC,Eidos Interactive,0.01,90.0,28.0,9.3,1069.0,Ion Storm,M,Eidos Interactive,Action role-playing,"Microsoft Windows, macOS","June 26, 2000"
920,Goat Simulator,XOne,Koch Media,0.01,53.0,15.0,6.3,63.0,Coffee Stain Studios,T,Coffee Stain Studios,"Nonlinear, sandbox physics","Microsoft Windows, Linux, macOS","April 1, 2014"
922,Icewind Dale II,PC,Interplay,0.01,83.0,22.0,8.3,147.0,Black Isle Studios,T,Interplay Entertainment,RPG,Microsoft Windows,"August 27, 2002"

In [10]:
newGamedf['id'] = newGamedf.groupby(['Name']).ngroup()
newGamedf = newGamedf.sort_values(by=['id'])
newGamedf

,Name,Platform,Publisher,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer_x,Rating,Producer,Genre_y,Operating System,Date Released,id
432,007: Quantum of Solace,PS3,Activision,1.14,65.0,42.0,6.6,47.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",0
433,007: Quantum of Solace,Wii,Activision,0.65,54.0,11.0,7.5,26.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",0
436,007: Quantum of Solace,PC,Activision,0.03,70.0,18.0,6.3,55.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",0
431,007: Quantum of Solace,X360,Activision,1.48,65.0,69.0,7.1,71.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",0
767,A Boy and His Blob,Wii,Majesco Entertainment,0.21,80.0,43.0,8.7,35.0,WayForward,E,"Midnight City, Majesco,",Adventure,"Microsoft Windows, Linux, macOS","January 19, 2016",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,XCOM: Enemy Unknown,PS3,Take-Two Interactive,0.57,89.0,20.0,8.2,296.0,Firaxis Games,M,"2K Games, Feral Interactive","Turn-based tactics, tactical role-playing","Microsoft Windows, Linux, macOS","October 9, 2012",336
667,XIII,XB,Ubisoft,0.25,74.0,38.0,8.3,15.0,Southend Interactive,M,Ubisoft,First-person shooter,"Microsoft Windows, macOS","November 18, 2003",337
666,XIII,PS2,Ubisoft,0.57,73.0,37.0,8.6,35.0,Ubisoft Paris,M,Ubisoft,First-person shooter,"Microsoft Windows, macOS","November 18, 2003",337
668,XIII,GC,Ubisoft,0.09,73.0,27.0,7.7,20.0,Ubisoft Paris,M,Ubisoft,First-person shooter,"Microsoft Windows, macOS","November 18, 2003",337
851,Zoo Tycoon 2,PC,Microsoft Game Studios,0.06,72.0,34.0,8.1,43.0,Blue Fang Games,E,"Microsoft Game Studios, MacSoft",Business simulation,"Microsoft Windows, macOS",November 2004,338

In [11]:
newGamedf['id'] += 1
newGamedf

,Name,Platform,Publisher,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer_x,Rating,Producer,Genre_y,Operating System,Date Released,id
432,007: Quantum of Solace,PS3,Activision,1.14,65.0,42.0,6.6,47.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",1
433,007: Quantum of Solace,Wii,Activision,0.65,54.0,11.0,7.5,26.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",1
436,007: Quantum of Solace,PC,Activision,0.03,70.0,18.0,6.3,55.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",1
431,007: Quantum of Solace,X360,Activision,1.48,65.0,69.0,7.1,71.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",1
767,A Boy and His Blob,Wii,Majesco Entertainment,0.21,80.0,43.0,8.7,35.0,WayForward,E,"Midnight City, Majesco,",Adventure,"Microsoft Windows, Linux, macOS","January 19, 2016",2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,XCOM: Enemy Unknown,PS3,Take-Two Interactive,0.57,89.0,20.0,8.2,296.0,Firaxis Games,M,"2K Games, Feral Interactive","Turn-based tactics, tactical role-playing","Microsoft Windows, Linux, macOS","October 9, 2012",337
667,XIII,XB,Ubisoft,0.25,74.0,38.0,8.3,15.0,Southend Interactive,M,Ubisoft,First-person shooter,"Microsoft Windows, macOS","November 18, 2003",338
666,XIII,PS2,Ubisoft,0.57,73.0,37.0,8.6,35.0,Ubisoft Paris,M,Ubisoft,First-person shooter,"Microsoft Windows, macOS","November 18, 2003",338
668,XIII,GC,Ubisoft,0.09,73.0,27.0,7.7,20.0,Ubisoft Paris,M,Ubisoft,First-person shooter,"Microsoft Windows, macOS","November 18, 2003",338
851,Zoo Tycoon 2,PC,Microsoft Game Studios,0.06,72.0,34.0,8.1,43.0,Blue Fang Games,E,"Microsoft Game Studios, MacSoft",Business simulation,"Microsoft Windows, macOS",November 2004,339

In [12]:
newGamedf = newGamedf.rename(columns={'Developer_x':'Developer','Genre_y':'Genre'})
newGamedf

,Name,Platform,Publisher,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,Producer,Genre,Operating System,Date Released,id
432,007: Quantum of Solace,PS3,Activision,1.14,65.0,42.0,6.6,47.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",1
433,007: Quantum of Solace,Wii,Activision,0.65,54.0,11.0,7.5,26.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",1
436,007: Quantum of Solace,PC,Activision,0.03,70.0,18.0,6.3,55.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",1
431,007: Quantum of Solace,X360,Activision,1.48,65.0,69.0,7.1,71.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",1
767,A Boy and His Blob,Wii,Majesco Entertainment,0.21,80.0,43.0,8.7,35.0,WayForward,E,"Midnight City, Majesco,",Adventure,"Microsoft Windows, Linux, macOS","January 19, 2016",2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,XCOM: Enemy Unknown,PS3,Take-Two Interactive,0.57,89.0,20.0,8.2,296.0,Firaxis Games,M,"2K Games, Feral Interactive","Turn-based tactics, tactical role-playing","Microsoft Windows, Linux, macOS","October 9, 2012",337
667,XIII,XB,Ubisoft,0.25,74.0,38.0,8.3,15.0,Southend Interactive,M,Ubisoft,First-person shooter,"Microsoft Windows, macOS","November 18, 2003",338
666,XIII,PS2,Ubisoft,0.57,73.0,37.0,8.6,35.0,Ubisoft Paris,M,Ubisoft,First-person shooter,"Microsoft Windows, macOS","November 18, 2003",338
668,XIII,GC,Ubisoft,0.09,73.0,27.0,7.7,20.0,Ubisoft Paris,M,Ubisoft,First-person shooter,"Microsoft Windows, macOS","November 18, 2003",338
851,Zoo Tycoon 2,PC,Microsoft Game Studios,0.06,72.0,34.0,8.1,43.0,Blue Fang Games,E,"Microsoft Game Studios, MacSoft",Business simulation,"Microsoft Windows, macOS",November 2004,339

# Steam Game Data Processing

In [13]:
steamG = pd.read_csv('steam_games.csv')
steamG

,url,types,name,desc_snippet,recent_reviews,all_reviews,release_date,developer,publisher,popular_tags,game_details,languages,achievements,genre,game_description,mature_content,minimum_requirements,recommended_requirements,original_price,discount_price
0,https://store.steampowered.com/app/379720/DOOM/,app,DOOM,Now includes all three premium DLC packs (Unto...,"Very Positive,(554),- 89% of the 554 user revi...","Very Positive,(42,550),- 92% of the 42,550 use...","May 12, 2016",id Software,"Bethesda Softworks,Bethesda Softworks","FPS,Gore,Action,Demons,Shooter,First-Person,Gr...","Single-player,Multi-player,Co-op,Steam Achieve...","English,French,Italian,German,Spanish - Spain,...",54.0,Action,"About This Game Developed by id software, the...",NaN,"Minimum:,OS:,Windows 7/8.1/10 (64-bit versions...","Recommended:,OS:,Windows 7/8.1/10 (64-bit vers...",$19.99,$14.99
1,https://store.steampowered.com/app/578080/PLAY...,app,PLAYERUNKNOWN'S BATTLEGROUNDS,PLAYERUNKNOWN'S BATTLEGROUNDS is a battle roya...,"Mixed,(6,214),- 49% of the 6,214 user reviews ...","Mixed,(836,608),- 49% of the 836,608 user revi...","Dec 21, 2017",PUBG Corporation,"PUBG Corporation,PUBG Corporation","Survival,Shooter,Multiplayer,Battle Royale,PvP...","Multi-player,Online Multi-Player,Stats","English,Korean,Simplified Chinese,French,Germa...",37.0,"Action,Adventure,Massively Multiplayer",About This Game PLAYERUNKNOWN'S BATTLEGROUND...,Mature Content Description The developers de...,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",$29.99,NaN
2,https://store.steampowered.com/app/637090/BATT...,app,BATTLETECH,Take command of your own mercenary outfit of '...,"Mixed,(166),- 54% of the 166 user reviews in t...","Mostly Positive,(7,030),- 71% of the 7,030 use...","Apr 24, 2018",Harebrained Schemes,"Paradox Interactive,Paradox Interactive","Mechs,Strategy,Turn-Based,Turn-Based Tactics,S...","Single-player,Multi-player,Online Multi-Player...","English,French,German,Russian",128.0,"Action,Adventure,Strategy",About This Game From original BATTLETECH/Mec...,NaN,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",$39.99,NaN
3,https://store.steampowered.com/app/221100/DayZ/,app,DayZ,The post-soviet country of Chernarus is struck...,"Mixed,(932),- 57% of the 932 user reviews in t...","Mixed,(167,115),- 61% of the 167,115 user revi...","Dec 13, 2018",Bohemia Interactive,"Bohemia Interactive,Bohemia Interactive","Survival,Zombies,Open World,Multiplayer,PvP,Ma...","Multi-player,Online Multi-Player,Steam Worksho...","English,French,Italian,German,Spanish - Spain,...",NaN,"Action,Adventure,Massively Multiplayer",About This Game The post-soviet country of Ch...,NaN,"Minimum:,OS:,Windows 7/8.1 64-bit,Processor:,I...","Recommended:,OS:,Windows 10 64-bit,Processor:,...",$44.99,NaN
4,https://store.steampowered.com/app/8500/EVE_On...,app,EVE Online,EVE Online is a community-driven spaceship MMO...,"Mixed,(287),- 54% of the 287 user reviews in t...","Mostly Positive,(11,481),- 74% of the 11,481 u...","May 6, 2003",CCP,"CCP,CCP","Space,Massively Multiplayer,Sci-fi,Sandbox,MMO...","Multi-player,Online Multi-Player,MMO,Co-op,Onl...","English,German,Russian,French",NaN,"Action,Free to Play,Massively Multiplayer,RPG,...",About This Game,NaN,"Minimum:,OS:,Windows 7,Processor:,Intel Dual C...","Recommended:,OS:,Windows 10,Processor:,Intel i...",Free,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40828,https://store.steampowered.com/app/899836/Rock...,app,Rocksmith® 2014 Edition – Remastered – Sabaton...,NaN,NaN,NaN,"Feb 12, 2019",Ubisoft - San Francisco,NaN,"Casual,Simulation","Single-player,Shared/Split Screen,Downloadable...","English,German,French,Italian,Spanish - Spain,...",NaN,"Casual,Simulation","About This Content Play ""Ghost Division"" by S...",NaN,"Minimum:,OS:,Windows Vista, Windows 7, Windows...","Recommended:,OS:,Windows Vista, Windows 7, Win...",$2.99,NaN
40829,https://store.steampowered.com/app/899832/Rock...,app,Rocksmith® 2014 Edition – Remastered – Stone T...,NaN,NaN,NaN,"Feb 5, 2019",Ubisoft - San Francisco,NaN,"Casual,Simulation","Single-player,Shared/Split Screen,Downloadable...","English,German,French,Italian,Spanish - Spain,...",NaN,"Casual,Simulation","About This Content Play ""Trippin’ on a Hole i...",NaN,"Minimum:,OS:,Windows Vista, Windows 7, Windows...","Recommended:,OS:,Windows Vista, Windows 7, Win...",$2.99,NaN
40830,https://store.steampowered.com/app/906840/Fant...,app,Fantasy Grounds - Quests of Doom 4: A Midnight...,NaN,NaN,NaN,"Jul 31, 2018","SmiteWorks USA, LLC",NaN,"RPG,Indie,Strategy,Software,Turn-Based,Fantasy...","Multi-player,Co-op,Cross-Platform Multiplayer,...",English,NaN,"Indie,RPG,Strategy",About This Content Quests of Doom 4: A Midni...,NaN,"Minimum:,OS:,Windows 7x , 8x or 10x,Processor:...","Recommended:,OS:,Windows 7x , 8x or 10x,Proces...",$7.99,NaN
40831,https://store.steampowered.com/app/906635/Mega...,app,Mega Man X5 Sound Collection,NaN,NaN,NaN,"Jul 24, 2018","CAPCOM CO., LTD","CAPCOM CO., LTD,CAPCOM CO., LTD",Action,"Single-player,Downloadable Content,Steam Achie...","English,French,Italian,German,Spanish - Spain,...",NaN,Action,About This Content Get equipped with the stun...,NaN,"Minimum:,OS:,WINDOWS® 7 (64bit),Processor:,Int...","Recommended:,OS:,WINDOWS®10 (64bit),Processor:...",$9.99,NaN
40832,https://store.steampowered.com/app/908000/Stor...,app,Stories In Stone,An RPG about a tribe exploring an ancient worl...,NaN,NaN,"Aug 8, 2018","16 Bit Psych,Kyle B","Self-Publish,Self-Publish","RPG,Adventure","Single-player,Partial Controller Support,Profi...",English,NaN,"Adventure,RPG",About This Game An RPG about a tribe explori...,NaN,NaN,NaN,$4.99,$2.80

In [14]:
ngDict = {}
stDict = {}

for nidx, nName in enumerate(newGamedf.Name):
    for sidx, sName in enumerate(steamG.name):
        if nName == sName:
            ngDict[nName] = nidx
            stDict[sName] = sidx

print(len(ngDict))
print(len(stDict))

86
86

In [15]:
for idx, row in newGamedf.iterrows():
    if row.Name in stDict and row.Platform == 'PC':
        print(row)
        newGamedf.loc[idx,'Platform'] = 'Steam'

Name                Air Conflicts: Secret Wars
Platform                                    PC
Publisher                    bitComposer Games
Global_Sales                              0.03
Critic_Score                              65.0
Critic_Count                               5.0
User_Score                                 6.4
User_Count                                24.0
Developer                           Games Farm
Rating                                       T
Producer                           bitComposer
Genre                        Flight simulation
Operating System             Microsoft Windows
Date Released               September 30, 2011
id                                          12
Name: 775, dtype: object
Name                                                        Alan Wake
Platform                                                           PC
Publisher                                                Nordic Games
Global_Sales                                                     0.06
Critic_Score                                                     83.0
Critic_Count                                                     30.0
User_Score                                                          8
User_Count                                                     1473.0
Developer                                        Remedy Entertainment
Rating                                                              T
Producer            Microsoft Game Studios, Remedy Entertainment, ...
Genre                                                 Survival horror
Operating System                                    Microsoft Windows
Date Released                                            May 14, 2010
id                                                                 13
Name: 475, dtype: object
Name                              BioShock Infinite
Platform                                         PC
Publisher                      Take-Two Interactive
Global_Sales                                   0.66
Critic_Score                                   94.0
Critic_Count                                   68.0
User_Score                                      8.5
User_Count                                   7322.0
Developer                          Irrational Games
Rating                                            M
Producer                                   2K Games
Genre                          First-person shooter
Operating System    Microsoft Windows, macOS, Linux
Date Released                        March 26, 2013
id                                               37
Name: 374, dtype: object
Name                                            Borderlands 2
Platform                                                   PC
Publisher                                Take-Two Interactive
Global_Sales                                             0.93
Critic_Score                                             89.0
Critic_Count                                             38.0
User_Score                                                8.2
User_Count                                             2482.0
Developer                                    Gearbox Software
Rating                                                      M
Producer                                             2K Games
Genre               Action role-playing, first-person shooter
Operating System              Microsoft Windows, Linux, macOS
Date Released                              September 18, 2012
id                                                         40
Name: 221, dtype: object
Name                                           Braid
Platform                                          PC
Publisher                                Number None
Global_Sales                                    0.03
Critic_Score                                    90.0
Critic_Count                                    11.0
User_Score                                       8.6
User_Count                                     819.0
Developer           Number None Inc., Knockout Games
Rating                                          E10+
Producer                                 Number None
Genre                               Puzzle, platform
Operating System     Microsoft Windows, Linux, macOS
Date Released                         April 10, 2009
id                                                41
Name: 889, dtype: object
Name                Burnout Paradise: The Ultimate Box
Platform                                            PC
Publisher                              Electronic Arts
Global_Sales                                      0.09
Critic_Score                                      87.0
Critic_Count                                      26.0
User_Score                                         7.5
User_Count                                       435.0
Developer                              Criterion Games
Rating                                            E10+
Producer                               Electronic Arts
Genre                                           Racing
Operating System                     Microsoft Windows
Date Released                         February 3, 2009
id                                                  43
Name: 819, dtype: object
Name                Call of Duty: World at War
Platform                                    PC
Publisher                           Activision
Global_Sales                              0.18
Critic_Score                              83.0
Critic_Count                              36.0
User_Score                                 7.5
User_Count                               721.0
Developer                             Treyarch
Rating                                       M
Producer                   Activision Blizzard
Genre                              Action, FPS
Operating System             Microsoft Windows
Date Released                November 11, 2008
id                                          52
Name: 68, dtype: object
Name                               Cities in Motion
Platform                                         PC
Publisher                       Paradox Interactive
Global_Sales                                   0.05
Critic_Score                                   70.0
Critic_Count                                   20.0
User_Score                                      7.7
User_Count                                    105.0
Developer                            Colossal Order
Rating                                            E
Producer                        Paradox Interactive
Genre                           Business simulation
Operating System    Microsoft Windows, Linux, macOS
Date Released                     February 23, 2011
id                                               54
Name: 857, dtype: object
Name                               Cities: Skylines
Platform                                         PC
Publisher                       Paradox Interactive
Global_Sales                                   0.14
Critic_Score                                   85.0
Critic_Count                                   60.0
User_Score                                      8.9
User_Count                                   1404.0
Developer                            Colossal Order
Rating                                            E
Producer                        Paradox Interactive
Genre                     City-building, Simulation
Operating System    Microsoft Windows, Linux, macOS
Date Released                        March 10, 2015
id                                               55
Name: 793, dtype: object
Name                Commandos 3: Destination Berlin
Platform                                         PC
Publisher                         Eidos Interactive
Global_Sales                                   0.02
Critic_Score                                   72.0
Critic_Count                                   24.0
User_Score                                      7.6
User_Count                                     83.0
Developer                              Pyro Studios
Rating                                            T
Producer                          Eidos Interactive
Genre                                           RTS
Operating System                  Microsoft Windows
Date Released                      October 23, 2003
id                                               61
Name: 910, dtype: object
Name                       Company of Heroes
Platform                                  PC
Publisher                                THQ
Global_Sales                            0.05
Critic_Score                            93.0
Critic_Count                            55.0
User_Score                               8.8
User_Count                            1128.0
Developer                              Relic
Rating                                     M
Producer                                 THQ
Genre                                    RTS
Operating System    Microsoft Windows, macOS
Date Released             September 12, 2006
id                                        63
Name: 865, dtype: object
Name                Company of Heroes 2
Platform                             PC
Publisher                           THQ
Global_Sales                       0.34
Critic_Score                       80.0
Critic_Count                       82.0
User_Score                          2.1
User_Count                       6157.0
Developer                         Relic
Rating                                M
Producer                           Sega
Genre                               RTS
Operating System      Microsoft Windows
Date Released             June 25, 2013
id                                   64
Name: 719, dtype: object
Name                         Counter-Strike: Source
Platform                                         PC
Publisher                             Vivendi Games
Global_Sales                                   0.08
Critic_Score                                   88.0
Critic_Count                                    9.0
User_Score                                      8.9
User_Count                                   9851.0
Developer                            Valve Software
Rating                                            M
Producer                                      Valve
Genre                          First-person shooter
Operating System    Microsoft Windows, Linux, macOS
Date Released                     September 1, 2004
id                                               67
Name: 831, dtype: object
Name                              Crysis
Platform                              PC
Publisher                Electronic Arts
Global_Sales                        0.71
Critic_Score                        91.0
Critic_Count                        56.0
User_Score                             8
User_Count                        1970.0
Developer                         Crytek
Rating                                 M
Producer                 Electronic Arts
Genre               First-person shooter
Operating System       Microsoft Windows
Date Released          November 13, 2007
id                                    68
Name: 622, dtype: object
Name                                           Dead Space
Platform                                               PC
Publisher                                 Electronic Arts
Global_Sales                                         0.59
Critic_Score                                         86.0
Critic_Count                                         28.0
User_Score                                              8
User_Count                                         1093.0
Developer                               EA Redwood Shores
Rating                                                  M
Producer                                  Electronic Arts
Genre               Survival horror, third-person shooter
Operating System                        Microsoft Windows
Date Released                             August 20, 2008
id                                                     76
Name: 369, dtype: object
Name                       Deus Ex: Mankind Divided
Platform                                         PC
Publisher                               Square Enix
Global_Sales                                   0.03
Critic_Score                                   83.0
Critic_Count                                   55.0
User_Score                                      6.1
User_Count                                    684.0
Developer           Eidos Montreal, Nixxes Software
Rating                                            M
Producer                                Square Enix
Genre                           Action role-playing
Operating System                  Microsoft Windows
Date Released                       August 23, 2016
id                                               83
Name: 709, dtype: object
Name                     Dragon Age: Origins
Platform                                  PC
Publisher                    Electronic Arts
Global_Sales                            0.51
Critic_Score                            91.0
Critic_Count                            67.0
User_Score                               8.6
User_Count                            3542.0
Developer                            BioWare
Rating                                     M
Producer                     Electronic Arts
Genre                           Role-playing
Operating System    Microsoft Windows, macOS
Date Released               November 3, 2009
id                                        91
Name: 287, dtype: object
Name                              Dungeon Defenders
Platform                                         PC
Publisher                                   Unknown
Global_Sales                                   0.02
Critic_Score                                   81.0
Critic_Count                                   26.0
User_Score                                      7.3
User_Count                                    399.0
Developer                      Trendy Entertainment
Rating                                         E10+
Producer                       Trendy Entertainment
Genre                     Tower defense, action RPG
Operating System    Microsoft Windows, Linux, macOS
Date Released                      October 19, 2011
id                                               96
Name: 904, dtype: object
Name                            Fallout 3
Platform                               PC
Publisher              Bethesda Softworks
Global_Sales                         0.98
Critic_Score                         91.0
Critic_Count                         48.0
User_Score                            7.9
User_Count                         3450.0
Developer           Bethesda Game Studios
Rating                                  M
Producer               Bethesda Softworks
Genre                                 RPG
Operating System        Microsoft Windows
Date Released            October 28, 2008
id                                    102
Name: 118, dtype: object
Name                            Fallout 4
Platform                               PC
Publisher              Bethesda Softworks
Global_Sales                         1.29
Critic_Score                         84.0
Critic_Count                         38.0
User_Score                            5.4
User_Count                         7512.0
Developer           Bethesda Game Studios
Rating                                  M
Producer               Bethesda Softworks
Genre                                 RPG
Operating System        Microsoft Windows
Date Released           November 10, 2015
id                                    103
Name: 74, dtype: object
Name                                    Fallout: New Vegas
Platform                                                PC
Publisher                               Bethesda Softworks
Global_Sales                                          1.17
Critic_Score                                          84.0
Critic_Count                                          39.0
User_Score                                             8.6
User_Count                                          2754.0
Developer                           Obsidian Entertainment
Rating                                                   M
Producer            Namco Bandai Games, Bethesda Softworks
Genre                                                  RPG
Operating System                         Microsoft Windows
Date Released                             October 19, 2010
id                                                     104
Name: 140, dtype: object
Name                           Far Cry 3
Platform                              PC
Publisher                        Ubisoft
Global_Sales                        0.96
Critic_Score                        88.0
Critic_Count                        43.0
User_Score                           8.2
User_Count                        3183.0
Developer               Ubisoft Montreal
Rating                                 M
Producer                         Ubisoft
Genre               First-person shooter
Operating System       Microsoft Windows
Date Released          November 29, 2012
id                                   107
Name: 198, dtype: object
Name                FlatOut: Ultimate Carnage
Platform                                   PC
Publisher                  Empire Interactive
Global_Sales                             0.01
Critic_Score                             79.0
Critic_Count                             16.0
User_Score                                7.7
User_Count                              127.0
Developer                             Bugbear
Rating                                      T
Producer            Valve, Empire Interactive
Genre                          Racing, arcade
Operating System            Microsoft Windows
Date Released                   July 22, 2007
id                                        119
Name: 813, dtype: object
Name                        Grand Theft Auto III
Platform                                      PC
Publisher                   Take-Two Interactive
Global_Sales                                0.01
Critic_Score                                93.0
Critic_Count                                20.0
User_Score                                   8.4
User_Count                                 805.0
Developer             DMA Design, Rockstar North
Rating                                         M
Producer                          Rockstar Games
Genre               Open world, action-adventure
Operating System               Microsoft Windows
Date Released                       May 21, 2002
id                                           127
Name: 29, dtype: object
Name                         Grand Theft Auto IV
Platform                                      PC
Publisher                   Take-Two Interactive
Global_Sales                                0.88
Critic_Score                                90.0
Critic_Count                                40.0
User_Score                                   6.6
User_Count                                2299.0
Developer                       Rockstar Toronto
Rating                                         M
Producer                          Rockstar Games
Genre               Open world, action-adventure
Operating System               Microsoft Windows
Date Released                   December 2, 2008
id                                           128
Name: 32, dtype: object
Name                          Grand Theft Auto V
Platform                                      PC
Publisher                   Take-Two Interactive
Global_Sales                                1.17
Critic_Score                                96.0
Critic_Count                                57.0
User_Score                                   7.9
User_Count                                3756.0
Developer                         Rockstar North
Rating                                         M
Producer                          Rockstar Games

In [16]:
# from math import isnan
# free = ['Free', 'Demo Middle-earth™: Shadow of War™', 'Play for Free!', 'Shadow of the Tomb Raider Free Trial', 'FINAL FANTASY XV WINDOWS EDITION PLAYABLE DEMO', \
#             'UNO', 'Demo', 'CrossCode Demo', 'EmergeNYC Demo', 'SpeedRunners Party Mode', ]
for idx, row in newGamedf.iterrows():
    if row.Name in stDict:
        if steamG.loc[stDict[row.Name],'original_price'][0] == '$':
            if float(steamG.loc[stDict[row.Name],'original_price'][1:]) != 0.0:
                newGamedf.loc[idx, 'IsF2P'] = False
            else:
                newGamedf.loc[idx, 'IsF2P'] = True
        else:
            newGamedf.loc[idx, 'IsF2P'] = True
    else:
        newGamedf.loc[idx, 'IsF2P'] = False
newGamedf

,Name,Platform,Publisher,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,Producer,Genre,Operating System,Date Released,id,IsF2P
432,007: Quantum of Solace,PS3,Activision,1.14,65.0,42.0,6.6,47.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",1,False
433,007: Quantum of Solace,Wii,Activision,0.65,54.0,11.0,7.5,26.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",1,False
436,007: Quantum of Solace,PC,Activision,0.03,70.0,18.0,6.3,55.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",1,False
431,007: Quantum of Solace,X360,Activision,1.48,65.0,69.0,7.1,71.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",1,False
767,A Boy and His Blob,Wii,Majesco Entertainment,0.21,80.0,43.0,8.7,35.0,WayForward,E,"Midnight City, Majesco,",Adventure,"Microsoft Windows, Linux, macOS","January 19, 2016",2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,XCOM: Enemy Unknown,PS3,Take-Two Interactive,0.57,89.0,20.0,8.2,296.0,Firaxis Games,M,"2K Games, Feral Interactive","Turn-based tactics, tactical role-playing","Microsoft Windows, Linux, macOS","October 9, 2012",337,False
667,XIII,XB,Ubisoft,0.25,74.0,38.0,8.3,15.0,Southend Interactive,M,Ubisoft,First-person shooter,"Microsoft Windows, macOS","November 18, 2003",338,False
666,XIII,PS2,Ubisoft,0.57,73.0,37.0,8.6,35.0,Ubisoft Paris,M,Ubisoft,First-person shooter,"Microsoft Windows, macOS","November 18, 2003",338,False
668,XIII,GC,Ubisoft,0.09,73.0,27.0,7.7,20.0,Ubisoft Paris,M,Ubisoft,First-person shooter,"Microsoft Windows, macOS","November 18, 2003",338,False
851,Zoo Tycoon 2,PC,Microsoft Game Studios,0.06,72.0,34.0,8.1,43.0,Blue Fang Games,E,"Microsoft Game Studios, MacSoft",Business simulation,"Microsoft Windows, macOS",November 2004,339,False

In [17]:
newGamedf[newGamedf.IsF2P==True]

,Name,Platform,Publisher,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,Producer,Genre,Operating System,Date Released,id,IsF2P
64,Call of Duty: World at War,X360,Activision,7.38,84.0,84.0,7.6,580.0,Treyarch,M,Activision Blizzard,"Action, FPS",Microsoft Windows,"November 11, 2008",52,True
65,Call of Duty: World at War,PS3,Activision,5.39,85.0,45.0,7.6,409.0,Treyarch,M,Activision Blizzard,"Action, FPS",Microsoft Windows,"November 11, 2008",52,True
67,Call of Duty: World at War,DS,Activision,0.89,75.0,12.0,7.8,20.0,n-Space,T,Activision Blizzard,"Action, FPS",Microsoft Windows,"November 11, 2008",52,True
68,Call of Duty: World at War,Steam,Activision,0.18,83.0,36.0,7.5,721.0,Treyarch,M,Activision Blizzard,"Action, FPS",Microsoft Windows,"November 11, 2008",52,True
66,Call of Duty: World at War,Wii,Activision,1.94,83.0,19.0,7.6,78.0,Exakt,M,Activision Blizzard,"Action, FPS",Microsoft Windows,"November 11, 2008",52,True
901,Star Trek Online,Steam,Atari,0.02,66.0,34.0,6.2,694.0,Cryptic Studios,T,Perfect World Entertainment,MMORPG,"Microsoft Windows, macOS","February 2, 2010",257,True

In [18]:
newGamedf = newGamedf.rename(columns={'Name':'GName', 'id':'GID', 'Global_Sales':'Sales', 'Date Released':'ReleasedDate'})
newGamedf

,GName,Platform,Publisher,Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,Producer,Genre,Operating System,ReleasedDate,GID,IsF2P
432,007: Quantum of Solace,PS3,Activision,1.14,65.0,42.0,6.6,47.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",1,False
433,007: Quantum of Solace,Wii,Activision,0.65,54.0,11.0,7.5,26.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",1,False
436,007: Quantum of Solace,PC,Activision,0.03,70.0,18.0,6.3,55.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",1,False
431,007: Quantum of Solace,X360,Activision,1.48,65.0,69.0,7.1,71.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",1,False
767,A Boy and His Blob,Wii,Majesco Entertainment,0.21,80.0,43.0,8.7,35.0,WayForward,E,"Midnight City, Majesco,",Adventure,"Microsoft Windows, Linux, macOS","January 19, 2016",2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,XCOM: Enemy Unknown,PS3,Take-Two Interactive,0.57,89.0,20.0,8.2,296.0,Firaxis Games,M,"2K Games, Feral Interactive","Turn-based tactics, tactical role-playing","Microsoft Windows, Linux, macOS","October 9, 2012",337,False
667,XIII,XB,Ubisoft,0.25,74.0,38.0,8.3,15.0,Southend Interactive,M,Ubisoft,First-person shooter,"Microsoft Windows, macOS","November 18, 2003",338,False
666,XIII,PS2,Ubisoft,0.57,73.0,37.0,8.6,35.0,Ubisoft Paris,M,Ubisoft,First-person shooter,"Microsoft Windows, macOS","November 18, 2003",338,False
668,XIII,GC,Ubisoft,0.09,73.0,27.0,7.7,20.0,Ubisoft Paris,M,Ubisoft,First-person shooter,"Microsoft Windows, macOS","November 18, 2003",338,False
851,Zoo Tycoon 2,PC,Microsoft Game Studios,0.06,72.0,34.0,8.1,43.0,Blue Fang Games,E,"Microsoft Game Studios, MacSoft",Business simulation,"Microsoft Windows, macOS",November 2004,339,False

# Game Table Generare

In [19]:
Game = newGamedf[['GID', 'GName', 'Sales', 'ReleasedDate', 'IsF2P']]
SalesSum = Game.groupby('GID')['Sales'].sum()
Game = Game.drop_duplicates('GID')
Game = Game.merge(SalesSum, on='GID')
Game = Game.set_index('GID')
Game = Game.drop(columns=['Sales_x'])
Game = Game.rename(columns={'Sales_y':'Sales'})
Game.round(2)    
Game

,GName,ReleasedDate,IsF2P,Sales
GID,,,,
1,007: Quantum of Solace,"October 31, 2008",False,3.30
2,A Boy and His Blob,"January 19, 2016",False,0.21
3,Ace Combat: Assault Horizon,"January 24, 2013",False,1.23
4,Activision Anthology,"November 19, 2002",False,0.50
5,Advent Rising,"May 31, 2005",False,0.13
...,...,...,...,...
335,World of Warcraft: Wrath of the Lich King,"November 13, 2008",False,1.32
336,X3: Terran Conflict,"October 16, 2008",False,0.03
337,XCOM: Enemy Unknown,"October 9, 2012",False,1.90
338,XIII,"November 18, 2003",False,0.91
339,Zoo Tycoon 2,November 2004,False,0.06

In [20]:
Game.ReleasedDate.unique()

array(['October 31, 2008', 'January 19, 2016', 'January 24, 2013',
       'November 19, 2002', 'May 31, 2005', 'September 30, 2005',
       'October 16, 2007', 'September 30, 1999', 'October 18, 2005',
       'November 2, 2007', 'October 30, 2002', 'September 30, 2011',
       'May 14, 2010', 'November 17, 2011', 'November 3, 2015',
       'July 14, 2005', 'October 14, 2010', 'November 13, 2007',
       'October 30, 2012', 'October 29, 2013', 'October 23, 2015',
       'November 16, 2010', 'November 15, 2011', 'November 8, 2013',
       'October 10, 1997', 'September 15, 2009', 'October 18, 2011',
       'June 2, 2015', 'October 25, 2013', 'September 10, 2002',
       'June 21, 2005', 'October 17, 2006', 'October 25, 2011',
       'August 21, 2007', 'February 9, 2010', 'March 26, 2013',
       'March 6, 2012', 'October 20, 2009', 'September 18, 2012',
       'April 10, 2009', 'September 23, 2008', 'February 3, 2009',
       'October 24, 2005', 'October 25, 2005', 'November 5, 2007',
       'November 9, 2010', 'November 5, 2013', 'November 4, 2016',
       'November 10, 2009', 'November 8, 2011', 'November 11, 2008',
       'October 5, 2010', 'February 23, 2011', 'March 10, 2015',
       'April 2, 2004', 'December 8, 2000', 'September 24, 2004',
       'August 25, 2002', 'September 21, 2001', 'October 23, 2003',
       'March 17, 2006', 'September 12, 2006', 'June 25, 2013',
       'February 14, 2005', 'June 19, 1999', 'September 1, 2004',
       'March 22, 2011', 'February 19, 2013', 'May 25, 2009',
       'August 23, 2012', 'April 24, 2014', 'April 12, 2016',
       'October 20, 2011', 'August 20, 2008', 'January 25, 2011',
       'February 5, 2013', 'March 24, 2003', 'June 26, 2000',
       'August 23, 2011', 'December 3, 2003', 'August 23, 2016',
       'December 31, 1996', 'June 29, 2000', 'May 15, 2012',
       'December 10, 1993', 'August 3, 2004', 'March 8, 2011',
       'November 18, 2014', 'November 3, 2009', 'May 22, 2012',
       'June 25, 1999', 'March 14, 2006', 'September 1, 2011',
       'October 19, 2011', 'November 12, 2001', 'April 26, 2005',
       'November 6, 2007', 'March 3, 2009', 'March 10, 2003',
       'October 28, 2008', 'November 10, 2015', 'October 19, 2010',
       'March 12, 2004', 'October 21, 2008', 'November 29, 2012',
       'May 27, 2014', 'September 17, 2014', 'April 14, 2016',
       'May 31, 1998', 'February 11, 1999', 'May 16, 2002',
       'October 9, 2014', 'December 11, 2014', 'November 5, 2004',
       'June 30, 2006', 'July 22, 2007', 'March 4, 2003',
       'August 1, 2008', 'April 1, 2014', 'January 14, 2022',
       'October 13, 2006', 'October 21, 1997', 'October 22, 1999',
       'May 21, 2002', 'December 2, 2008', 'April 14, 2015',
       'June 7, 2005', 'May 12, 2003', 'August 28, 2012',
       'November 19, 1998', 'November 16, 2004', 'May 17, 2007',
       'September 30, 2003', 'August 7, 2009', 'October 1, 2002',
       'November 19, 2012', 'May 30, 2006', 'April 20, 2004',
       'November 3, 2000', 'September 28, 1999', 'September 16, 2003',
       'August 27, 2002', 'February 26, 2007', 'November 28, 2002',
       'November 16, 2007', 'September 22, 2006', 'March 23, 2010',
       'December 1, 2015', 'February 7, 2012', 'May 17, 2011',
       'December 8, 2014', 'November 11, 2014', 'December 10, 2015',
       'February 22, 2005', 'November 20, 2007', 'January 26, 2010',
       'July 23, 2001', 'October 14, 2003', 'October 8, 2010',
       'October 23, 2012', 'November 11, 2006', 'January 9, 2014',
       'September 3, 1998', 'March 27, 2003', 'September 1, 2015',
       'March 16, 2010', 'May 14, 2013', 'November 12, 2008',
       'April 13, 2015', '1994', 'October 12, 2009', 'October 4, 2011',
       'October 2, 2012', 'November 15, 2013', 'October 7, 2014',
       'September 29, 2016', 'September 20, 2016', 'October 7, 2008',
       'October 4, 2005', 'November 15, 2006', 'February 7, 2001',
       'October 8, 2002', 'October 15, 2003', 'September 28, 2004',
       'February 23, 2010', 'October 2, 2002', 'February 29, 2000',
       'June 18, 2002', 'October 31, 2006', 'October 9, 2007',
       'July 23, 2005', 'August 9, 2016', 'September 22, 2009',
       'May 24, 2016', 'September 15, 2006', 'August 13, 2013',
       'March 26, 2015', 'March 4, 2005', 'April 19, 2011',
       'November 6, 2003', 'November 30, 2004', 'October 6, 2015',
       'October 27, 2003', 'September 3, 2013', 'March 29, 2012',
       'September 13, 2011', 'March 22, 1996', 'January 21, 1998',
       'September 22, 1999', 'January 11, 2005', 'March 5, 2009',
       'March 20, 2012', 'January 26, 2012',
       'February 24 2015; March 3, 2015; March 10, 2015; March 17, 2015',
       'March 27, 2015', 'May 20, 2003', 'May 9, 2006',
       'January 28, 2016', 'July 7, 2015', 'March 31, 1999',
       'October 15, 2002', 'October 26, 2004', 'November 22, 2004',
       'October 10, 2014', 'February 2, 2010', 'September 15, 2008',
       'March 20, 2007', 'April 5, 2005', 'January 5, 2009',
       'August 20, 2013', 'March 2, 2010', 'March 15, 2005',
       'March 5, 2013', 'January 14, 2003', '2008', 'September 14, 2012',
       'December 5, 2003', 'September 7, 2008', 'November 19, 2003',
       'February 17, 2005', 'December 20, 2011', 'March 31, 1998',
       'March 12, 2013', 'July 27, 2010', 'October 19, 2001',
       'November 16, 2018', 'February 16, 2007', 'May 30, 2007',
       'May 16, 2011', 'February 7, 2008', 'May 1, 2002',
       'March 20, 2006', 'April 4, 2014', 'November 11, 2011',
       'July 3, 2012', 'June 30, 1993', 'March 25, 2010',
       'November 28, 2007', 'February 11, 2000', 'September 14, 2004',
       'August 25, 2008', 'September 4, 2007', 'September 13, 2005',
       'March 6, 2006', 'February 23, 2007', 'March 11, 2005',
       'June 2, 2009', 'May 31, 2011', 'November 13, 2012',
       'November 14, 2001', 'April 2, 2001', 'October 29, 2003',
       'May 13, 2003', 'January 7, 2002', 'March 28, 2002',
       'October 26, 2007', 'May 19, 2015', 'May 25, 2004',
       'June 26, 2006', 'November 17, 2002', 'March 21, 2005',
       'April 13, 2010', 'March 23, 2004', 'November 14, 1996',
       'June 1, 2007', 'April 7, 2006', 'November 18, 2008',
       'October 27, 2009', 'April 15, 2011', 'August 26, 2011',
       'May 23, 2014', 'February 3, 2003', 'November 30, 1999',
       'March 16, 2004', 'July 3, 2002', 'February 19, 2009',
       'September 19, 2014', 'September 18, 2007', 'November 21, 2017',
       'October 13, 2008', 'April 12, 2011', 'November 23, 2004',
       'December 7, 2010', 'August 30, 2016', 'July 25, 2012',
       'January 15, 2007', 'November 13, 2014', 'November 13, 2008',
       'October 16, 2008', 'October 9, 2012', 'November 18, 2003',
       'November 2004'], dtype=object)

In [21]:
import calendar

monthName2numb = {month: index for index, month in enumerate(calendar.month_name) if month}

In [22]:
Game

,GName,ReleasedDate,IsF2P,Sales
GID,,,,
1,007: Quantum of Solace,"October 31, 2008",False,3.30
2,A Boy and His Blob,"January 19, 2016",False,0.21
3,Ace Combat: Assault Horizon,"January 24, 2013",False,1.23
4,Activision Anthology,"November 19, 2002",False,0.50
5,Advent Rising,"May 31, 2005",False,0.13
...,...,...,...,...
335,World of Warcraft: Wrath of the Lich King,"November 13, 2008",False,1.32
336,X3: Terran Conflict,"October 16, 2008",False,0.03
337,XCOM: Enemy Unknown,"October 9, 2012",False,1.90
338,XIII,"November 18, 2003",False,0.91
339,Zoo Tycoon 2,November 2004,False,0.06

In [23]:
for idx, row in Game.iterrows():
    try:
        test = int(row.ReleasedDate[0])
    except:
        try:
            monthday, year = row.ReleasedDate.split(',')
            month, day = monthday.split()
        except:
            if len(row.ReleasedDate.split(';')) != 1:
                date = row.ReleasedDate.split(';')[0]
                month, day, year = date.split()
            else:
                month, year = row.ReleasedDate.split()
                day = 1
        monthNum = monthName2numb[month]
        newdate = f"{int(monthNum)}-{int(day)}-{int(year)}"
        Game.loc[idx, "ReleasedDate"] = newdate

Game

                                         GName ReleasedDate  IsF2P  Sales
GID
1                       007: Quantum of Solace   10-31-2008  False   3.30
2                           A Boy and His Blob    1-19-2016  False   0.21
3                  Ace Combat: Assault Horizon    1-24-2013  False   1.23
4                         Activision Anthology   11-19-2002  False   0.50
5                                Advent Rising    5-31-2005  False   0.13
..                                         ...          ...    ...    ...
335  World of Warcraft: Wrath of the Lich King   11-13-2008  False   1.32
336                        X3: Terran Conflict   10-16-2008  False   0.03
337                        XCOM: Enemy Unknown    10-9-2012  False   1.90
338                                       XIII   11-18-2003  False   0.91
339                               Zoo Tycoon 2    11-1-2004  False   0.06

[339 rows x 4 columns]

In [24]:
Game['ReleasedDate'] = pd.to_datetime(Game['ReleasedDate'])
Game.info

<bound method DataFrame.info of                                          GName ReleasedDate  IsF2P  Sales
GID
1                       007: Quantum of Solace   2008-10-31  False   3.30
2                           A Boy and His Blob   2016-01-19  False   0.21
3                  Ace Combat: Assault Horizon   2013-01-24  False   1.23
4                         Activision Anthology   2002-11-19  False   0.50
5                                Advent Rising   2005-05-31  False   0.13
..                                         ...          ...    ...    ...
335  World of Warcraft: Wrath of the Lich King   2008-11-13  False   1.32
336                        X3: Terran Conflict   2008-10-16  False   0.03
337                        XCOM: Enemy Unknown   2012-10-09  False   1.90
338                                       XIII   2003-11-18  False   0.91
339                               Zoo Tycoon 2   2004-11-01  False   0.06

[339 rows x 4 columns]>

In [25]:
os.makedirs('clean', exist_ok=True)
Game = Game[['GName', 'Sales', 'ReleasedDate', 'IsF2P']]
Game.to_csv('clean/Game.csv')

# GameHasGenre Relation Table

In [26]:
GameHasGenre = newGamedf[['GID', 'Genre']].drop_duplicates()
GameHasGenre = GameHasGenre.set_index('GID')
GameHasGenre

                                         Genre
GID
1                         First-person shooter
2                                    Adventure
3                      Combat flight simulator
4                                  Compilation
5       Action-adventure, third-person shooter
..                                         ...
335                   Online role-playing game
336                           Space simulation
337  Turn-based tactics, tactical role-playing
338                       First-person shooter
339                        Business simulation

[339 rows x 1 columns]

In [27]:
for idx, row in GameHasGenre.iterrows():
    if len(row.Genre.split(',')) != 1:
        newGenre = row.Genre.replace(',', '/')
        newGenre.strip()
        newGenre.lstrip()
        newGenre.rstrip()
        GameHasGenre.loc[idx, 'Genre'] = newGenre

GameHasGenre

                                         Genre
GID
1                         First-person shooter
2                                    Adventure
3                      Combat flight simulator
4                                  Compilation
5       Action-adventure/ third-person shooter
..                                         ...
335                   Online role-playing game
336                           Space simulation
337  Turn-based tactics/ tactical role-playing
338                       First-person shooter
339                        Business simulation

[339 rows x 1 columns]

In [28]:
GameHasGenre

                                         Genre
GID
1                         First-person shooter
2                                    Adventure
3                      Combat flight simulator
4                                  Compilation
5       Action-adventure/ third-person shooter
..                                         ...
335                   Online role-playing game
336                           Space simulation
337  Turn-based tactics/ tactical role-playing
338                       First-person shooter
339                        Business simulation

[339 rows x 1 columns]

In [29]:
GameHasGenre = GameHasGenre.reset_index()
j = GameHasGenre.shape[0]

for idx, row in GameHasGenre.iterrows():
    g = row.Genre.split('/')
    if len(g) != 1:
        GameHasGenre.loc[idx, 'Genre'] = g[0].strip().rstrip().lstrip()
        gid = row.GID
        for othergenre in g[1:]:
            GameHasGenre.loc[j] = [gid, othergenre.strip().rstrip().lstrip()]
            j+=1
GameHasGenre

     GID                    Genre
0      1     First-person shooter
1      2                Adventure
2      3  Combat flight simulator
3      4              Compilation
4      5         Action-adventure
..   ...                      ...
443  315       City-building game
444  316       City-building game
445  317       City-building game
446  328                      MMO
447  337    tactical role-playing

[448 rows x 2 columns]

In [30]:
GameHasGenre = GameHasGenre.sort_values('GID')

In [31]:
import csv
GameHasGenre.to_csv('clean/GameHasGenre.csv', quoting=csv.QUOTE_NONE, index=False)

# Game Platform Relation Table

In [32]:
GP = newGamedf[['GID', 'Platform']]
GP['PID'] = GP.groupby(['Platform']).ngroup() + 1
GP

/var/folders/1w/69830wnn68lcddbj958q9t1w0000gn/T/ipykernel_4323/3954506576.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GP['PID'] = GP.groupby(['Platform']).ngroup() + 1

     GID Platform  PID
432    1      PS3    8
433    1      Wii   13
436    1       PC    5
431    1     X360   15
767    2      Wii   13
..   ...      ...  ...
621  337      PS3    8
667  338       XB   16
666  338      PS2    7
668  338       GC    4
851  339       PC    5

[701 rows x 3 columns]

In [33]:
Platform = GP[['PID', 'Platform']].drop_duplicates()
Platform = Platform.sort_values('PID')
Platform = Platform.set_index('PID')
Platform

    Platform
PID
1        3DS
2         DS
3        GBA
4         GC
5         PC
6         PS
7        PS2
8        PS3
9        PS4
10       PSP
11       PSV
12     Steam
13       Wii
14      WiiU
15      X360
16        XB
17      XOne

In [34]:
from datetime import date

foundDateDict = {'3DS':date(2011,2,26), 'DS':date(2004, 11, 21), 'GBA':date(2001, 3, 21), 'GC':date(2001, 9, 14), 'PC':date(1971, 1, 1), 'PS':date(1994, 12, 3), 'PS2':date(2000, 3, 4), 'PS3':date(2006, 11, 11),\
                'PS4':date(2013, 11, 15), 'PSP':date(2004, 12, 12), 'PSV':date(2012, 2, 22), 'Steam':date(2003, 9, 12), 'Wii':date(2006, 11, 19), 'WiiU':date(2012, 11, 18), 'X360':date(2005, 11, 22), 'XB':date(2001,11,15),\
                'XOne':date(2013, 11, 22)}

Platform['FoundDate'] = Platform['Platform'].map(foundDateDict)
Platform = Platform.rename(columns={'Platform':'PName'})
Platform

     PName   FoundDate
PID
1      3DS  2011-02-26
2       DS  2004-11-21
3      GBA  2001-03-21
4       GC  2001-09-14
5       PC  1971-01-01
6       PS  1994-12-03
7      PS2  2000-03-04
8      PS3  2006-11-11
9      PS4  2013-11-15
10     PSP  2004-12-12
11     PSV  2012-02-22
12   Steam  2003-09-12
13     Wii  2006-11-19
14    WiiU  2012-11-18
15    X360  2005-11-22
16      XB  2001-11-15
17    XOne  2013-11-22

In [35]:
Platform.to_csv('clean/platform.csv')

In [36]:
PlatformHostsGame = GP[['PID', 'GID']]
PlatformHostsGame = PlatformHostsGame

In [37]:
PlatformHostsGame.to_csv('clean/PlatformHostsGame.csv', index=False)

# GameIsAvailableOn Relation Table

In [38]:
newGamedf

,GName,Platform,Publisher,Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,Producer,Genre,Operating System,ReleasedDate,GID,IsF2P
432,007: Quantum of Solace,PS3,Activision,1.14,65.0,42.0,6.6,47.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",1,False
433,007: Quantum of Solace,Wii,Activision,0.65,54.0,11.0,7.5,26.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",1,False
436,007: Quantum of Solace,PC,Activision,0.03,70.0,18.0,6.3,55.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",1,False
431,007: Quantum of Solace,X360,Activision,1.48,65.0,69.0,7.1,71.0,Treyarch,T,"Activision, Square Enix",First-person shooter,Microsoft Windows,"October 31, 2008",1,False
767,A Boy and His Blob,Wii,Majesco Entertainment,0.21,80.0,43.0,8.7,35.0,WayForward,E,"Midnight City, Majesco,",Adventure,"Microsoft Windows, Linux, macOS","January 19, 2016",2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,XCOM: Enemy Unknown,PS3,Take-Two Interactive,0.57,89.0,20.0,8.2,296.0,Firaxis Games,M,"2K Games, Feral Interactive","Turn-based tactics, tactical role-playing","Microsoft Windows, Linux, macOS","October 9, 2012",337,False
667,XIII,XB,Ubisoft,0.25,74.0,38.0,8.3,15.0,Southend Interactive,M,Ubisoft,First-person shooter,"Microsoft Windows, macOS","November 18, 2003",338,False
666,XIII,PS2,Ubisoft,0.57,73.0,37.0,8.6,35.0,Ubisoft Paris,M,Ubisoft,First-person shooter,"Microsoft Windows, macOS","November 18, 2003",338,False
668,XIII,GC,Ubisoft,0.09,73.0,27.0,7.7,20.0,Ubisoft Paris,M,Ubisoft,First-person shooter,"Microsoft Windows, macOS","November 18, 2003",338,False
851,Zoo Tycoon 2,PC,Microsoft Game Studios,0.06,72.0,34.0,8.1,43.0,Blue Fang Games,E,"Microsoft Game Studios, MacSoft",Business simulation,"Microsoft Windows, macOS",November 2004,339,False

In [39]:
GameIsAvailableOn = newGamedf[['GID', 'Operating System']].drop_duplicates()
GameIsAvailableOn = GameIsAvailableOn.rename(columns={'Operating System': 'OS'}).set_index('GID')
GameIsAvailableOn

                                  OS
GID
1                  Microsoft Windows
2    Microsoft Windows, Linux, macOS
3                  Microsoft Windows
4       Microsoft Windows, Macintosh
5                  Microsoft Windows
..                               ...
335         Microsoft Windows, macOS
336  Microsoft Windows, Linux, macOS
337  Microsoft Windows, Linux, macOS
338         Microsoft Windows, macOS
339         Microsoft Windows, macOS

[339 rows x 1 columns]

In [40]:
for idx, row in GameIsAvailableOn.iterrows():
    if len(row.OS.split(',')) != 1:
        newOS = row.OS.replace(',', '/')
        newOS.strip()
        newOS.lstrip()
        newOS.rstrip()
        GameIsAvailableOn.loc[idx, 'OS'] = newOS

GameIsAvailableOn

                                  OS
GID
1                  Microsoft Windows
2    Microsoft Windows/ Linux/ macOS
3                  Microsoft Windows
4       Microsoft Windows/ Macintosh
5                  Microsoft Windows
..                               ...
335         Microsoft Windows/ macOS
336  Microsoft Windows/ Linux/ macOS
337  Microsoft Windows/ Linux/ macOS
338         Microsoft Windows/ macOS
339         Microsoft Windows/ macOS

[339 rows x 1 columns]

In [41]:
GameIsAvailableOn

                                  OS
GID
1                  Microsoft Windows
2    Microsoft Windows/ Linux/ macOS
3                  Microsoft Windows
4       Microsoft Windows/ Macintosh
5                  Microsoft Windows
..                               ...
335         Microsoft Windows/ macOS
336  Microsoft Windows/ Linux/ macOS
337  Microsoft Windows/ Linux/ macOS
338         Microsoft Windows/ macOS
339         Microsoft Windows/ macOS

[339 rows x 1 columns]

In [42]:
GameIsAvailableOn = GameIsAvailableOn.reset_index()
m = GameIsAvailableOn.shape[0]

for idx, row in GameIsAvailableOn.iterrows():
    o = row.OS.split('/')
    if len(o) != 1:
        GameIsAvailableOn.loc[idx, 'OS'] = o[0].strip().rstrip().lstrip()
        gid = row.GID
        for otheros in o[1:]:
            GameIsAvailableOn.loc[m] = [gid, otheros.strip().rstrip().lstrip()]
            m+=1
GameIsAvailableOn

     GID                 OS
0      1  Microsoft Windows
1      2  Microsoft Windows
2      3  Microsoft Windows
3      4  Microsoft Windows
4      5  Microsoft Windows
..   ...                ...
503  336              macOS
504  337              Linux
505  337              macOS
506  338              macOS
507  339              macOS

[508 rows x 2 columns]

In [43]:
GameIsAvailableOn = GameIsAvailableOn.sort_values('GID')
GameIsAvailableOn

     GID                 OS
0      1  Microsoft Windows
340    2              macOS
339    2              Linux
1      2  Microsoft Windows
2      3  Microsoft Windows
..   ...                ...
505  337              macOS
337  338  Microsoft Windows
506  338              macOS
338  339  Microsoft Windows
507  339              macOS

[508 rows x 2 columns]

In [44]:
GameIsAvailableOn.to_csv('clean/GameIsAvailableOn.csv', quoting=csv.QUOTE_NONE, index=False)

# Award Dataset

In [45]:
award = pd.read_csv('the_game_awards.csv')
award.head(10)

,year,category,nominee,company,winner,voted
0,2014,Game of the Year,Dragon Age: Inquisition,BioWare,1,jury
1,2014,Game of the Year,Bayonetta 2,Platinum Games,0,jury
2,2014,Game of the Year,Dark Souls II,FromSoftware,0,jury
3,2014,Game of the Year,Hearthstone: Heroes of Warcraft,Blizzard Entertainment,0,jury
4,2014,Game of the Year,Middle-earth: Shadow of Mordor,Monolith Productions,0,jury
5,2014,Developer of the Year,Nintendo Entertainment Analysis and Development,Nintendo,1,jury
6,2014,Developer of the Year,Blizzard Entertainment,Blizzard Entertainment,0,jury
7,2014,Developer of the Year,Monolith Productions,Monolith Productions,0,jury
8,2014,Developer of the Year,Telltale Games,Telltale Games,0,jury
9,2014,Developer of the Year,Ubisoft Montreal,Ubisoft Montreal,0,jury

In [46]:
games = set(newGamedf.GName.unique().tolist())
NameID = {}
for idx, row in newGamedf.iterrows():
    NameID[row.GName] = row.GID

ctr = 0
gameid = max(newGamedf.GID)
for idx, row in award.iterrows():
    if row.nominee in games:
        ctr += 1
        award.loc[idx,'GID'] = NameID[row.nominee]
    else:
        award.drop(index=idx, axis=0, inplace=True)
award = award.astype({'GID':'int'})
print("number of games awarded that is in the game table",ctr)
print("number of games in the game table in total: ", len(games))

number of games awarded that is in the game table 69
number of games in the game table in total:  339

In [47]:
award['AID'] = award.groupby(['category']).ngroup()
award

,year,category,nominee,company,winner,voted,GID,AID
0,2014,Game of the Year,Dragon Age: Inquisition,BioWare,1,jury,90,24
2,2014,Game of the Year,Dark Souls II,FromSoftware,0,jury,73,24
10,2014,Best Shooter,Far Cry 4,Ubisoft Montreal,1,jury,108,18
19,2014,Best Action/Adventure,Sunset Overdrive,Insomniac Games/Microsoft Studios),0,jury,267,1
23,2014,Best Sports/Racing Game,NBA 2K15,Visual Concepts/2K Sports),0,jury,184,19
...,...,...,...,...,...,...,...,...
649,2019,Best Game Direction,Resident Evil 2,Capcom,0,jury,221,7
677,2019,Best Audio Design,Resident Evil 2,Capcom,0,jury,221,4
703,2019,Best VR/AR Game,No Man's Sky,Hello Games,0,jury,202,20
715,2019,Best Action/Adventure Game,Resident Evil 2,Capcom,0,jury,221,2
772,2019,Best Esports Game,Overwatch,Blizzard Entertainment,0,jury,204,5

In [48]:
award = award.rename(columns={'category':'AName','voted':"votedByWho"})
award

,year,AName,nominee,company,winner,votedByWho,GID,AID
0,2014,Game of the Year,Dragon Age: Inquisition,BioWare,1,jury,90,24
2,2014,Game of the Year,Dark Souls II,FromSoftware,0,jury,73,24
10,2014,Best Shooter,Far Cry 4,Ubisoft Montreal,1,jury,108,18
19,2014,Best Action/Adventure,Sunset Overdrive,Insomniac Games/Microsoft Studios),0,jury,267,1
23,2014,Best Sports/Racing Game,NBA 2K15,Visual Concepts/2K Sports),0,jury,184,19
...,...,...,...,...,...,...,...,...
649,2019,Best Game Direction,Resident Evil 2,Capcom,0,jury,221,7
677,2019,Best Audio Design,Resident Evil 2,Capcom,0,jury,221,4
703,2019,Best VR/AR Game,No Man's Sky,Hello Games,0,jury,202,20
715,2019,Best Action/Adventure Game,Resident Evil 2,Capcom,0,jury,221,2
772,2019,Best Esports Game,Overwatch,Blizzard Entertainment,0,jury,204,5

In [49]:
awardTable = award[['AID','AName', 'votedByWho']].drop_duplicates()
awardTable = awardTable.set_index('AID')
awardTable = awardTable.sort_index()
awardTable

                          AName votedByWho
AID
0              Best Action Game       jury
1         Best Action/Adventure       jury
2    Best Action/Adventure Game       jury
3            Best Art Direction       jury
4             Best Audio Design       jury
5             Best Esports Game       jury
6            Best Fighting Game       jury
7           Best Game Direction       jury
8         Best Independent Game       jury
9              Best Multiplayer       jury
10      Best Music/Sound Design       jury
11               Best Narrative       jury
12            Best Ongoing Game       jury
13       Best Online Experience       jury
14                Best Remaster       jury
15       Best Role Playing Game       jury
16             Best Score/Music       jury
17        Best Score/Soundtrack       jury
18                 Best Shooter       jury
19      Best Sports/Racing Game       jury
20              Best VR/AR Game       jury
21            Best eSports Game        fan
22        Developer of the Year       jury
23     ESports Game of the Year        fan
24             Game of the Year       jury
25        Most Anticipated Game        fan
26   Most Anticipated Game 2015        fan

In [50]:
awardTable.to_csv('clean/award.csv')

# GameNominatedByAward Relation Table

In [51]:
award = award.rename(columns={'year':'Year', 'winner':'DidWin'})
GameNominatedByAward = award[['GID', 'AID', 'Year', 'DidWin']]
GameNominatedByAward.set_index('GID')

     AID  Year  DidWin
GID
90    24  2014       1
73    24  2014       0
108   18  2014       1
267    1  2014       0
184   19  2014       0
..   ...   ...     ...
221    7  2019       0
221    4  2019       0
202   20  2019       0
221    2  2019       0
204    5  2019       0

[69 rows x 3 columns]

In [52]:
GameNominatedByAward.to_csv('clean/GameNominatedByAward.csv')

# Company Entity

In [53]:
company = pd.read_csv('GamingCompanies-Main.csv')
company

,Name,marketcap,earnings,employeeCount,OperatingMargin,PERatio,Revenue,country
0,11 bit studios,2.600171e+08,8147710,192,4583.070,40.888100,1.777785e+07,Poland
1,Activision Blizzard,5.835960e+10,2972000000,9500,3582.020,23.471700,8.297000e+09,United States
2,Appirits,3.008261e+07,1591300,411,372.253,31.000000,4.274776e+07,Japan
3,Aristocrat,1.551363e+10,778411000,7000,2266.820,14.297000,3.433941e+09,Australia
4,ATARI,4.923000e+07,-13476800,26,-6296.300,-3.000000,2.140430e+07,France
...,...,...,...,...,...,...,...,...
74,Unity Software,9.993398e+09,-590918000,4934,-4941.280,-16.076200,1.195880e+09,United States
75,Versus Systems,1.169109e+07,-11545800,0,-153192.000,-0.823529,7.536780e+05,Canada
76,Webzen,5.007477e+08,0,0,0.000,0.000000,0.000000e+00,South Korea
77,Wemade,8.686795e+08,0,0,0.000,0.000000,0.000000e+00,South Korea
78,WonderPlanet,3.043914e+07,-1386590,0,-498.975,4.037680,2.778869e+07,Japan

In [54]:
company['CID'] = company.groupby(['Name']).ngroup()
company = company.rename(columns={'Name':'CName', 'marketcap':'MarketCap', 'earnings':'Earnings', 'employeeCount':'EmployeeCount', 'country':'Country'})
company

,CName,MarketCap,Earnings,EmployeeCount,OperatingMargin,PERatio,Revenue,Country,CID
0,11 bit studios,2.600171e+08,8147710,192,4583.070,40.888100,1.777785e+07,Poland,0
1,Activision Blizzard,5.835960e+10,2972000000,9500,3582.020,23.471700,8.297000e+09,United States,2
2,Appirits,3.008261e+07,1591300,411,372.253,31.000000,4.274776e+07,Japan,3
3,Aristocrat,1.551363e+10,778411000,7000,2266.820,14.297000,3.433941e+09,Australia,4
4,ATARI,4.923000e+07,-13476800,26,-6296.300,-3.000000,2.140430e+07,France,1
...,...,...,...,...,...,...,...,...,...
74,Unity Software,9.993398e+09,-590918000,4934,-4941.280,-16.076200,1.195880e+09,United States,71
75,Versus Systems,1.169109e+07,-11545800,0,-153192.000,-0.823529,7.536780e+05,Canada,72
76,Webzen,5.007477e+08,0,0,0.000,0.000000,0.000000e+00,South Korea,73
77,Wemade,8.686795e+08,0,0,0.000,0.000000,0.000000e+00,South Korea,74
78,WonderPlanet,3.043914e+07,-1386590,0,-498.975,4.037680,2.778869e+07,Japan,75

In [55]:
company = company[['CID', 'CName', 'MarketCap', 'Earnings', 'EmployeeCount', 'Revenue', 'Country']]
company.loc[79] = [79, "Valve", None, None, None, None, "United States"]

/var/folders/1w/69830wnn68lcddbj958q9t1w0000gn/T/ipykernel_4323/2357230199.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  company.loc[79] = [79, "Valve", None, None, None, None, "United States"]

In [56]:
companyoutput = company.set_index('CID')

In [57]:
companyoutput = companyoutput.sort_index()
companyoutput

,CName,MarketCap,Earnings,EmployeeCount,Revenue,Country
CID,,,,,,
0,11 bit studios,2.600171e+08,8147710,192,1.777785e+07,Poland
1,ATARI,4.923000e+07,-13476800,26,2.140430e+07,France
2,Activision Blizzard,5.835960e+10,2972000000,9500,8.297000e+09,United States
3,Appirits,3.008261e+07,1591300,411,4.274776e+07,Japan
4,Aristocrat,1.551363e+10,778411000,7000,3.433941e+09,Australia
...,...,...,...,...,...,...
75,WonderPlanet,3.043914e+07,-1386590,0,2.778869e+07,Japan
76,enish,3.597796e+07,1383920,100,4.062834e+07,Japan
77,geechs,7.427060e+07,10611300,357,4.921509e+07,Japan
78,gumi,1.243233e+08,-34557000,866,1.593100e+08,Japan
79,Valve,NaN,None,None,NaN,United States

In [58]:
companyoutput.to_csv('clean/company.csv')

# CompanyOwnsGame Relation Table

In [59]:
from collections import defaultdict
newGame_gid_company = defaultdict(list)
cname_cid = {}

for idx, row in newGamedf.iterrows():
    c = row.Publisher
    if row.GID not in newGame_gid_company[c]:
        newGame_gid_company[c].append(row.GID)

for idx, row in company.iterrows():
    cname_cid[row.CName] = row.CID

In [60]:
print(newGame_gid_company.keys())
print(cname_cid.keys())

dict_keys(['Activision', 'Majesco Entertainment', 'Namco Bandai Games', 'THQ', 'The Adventure Company', 'Microsoft Game Studios', 'bitComposer Games', 'Nordic Games', 'Ubisoft', 'Metro 3D', 'JoWood Productions', '505 Games', 'Infogrames', 'Eidos Interactive', 'Warner Bros. Interactive Entertainment', 'Electronic Arts', 'Take-Two Interactive', 'Konami Digital Entertainment', 'Number None', 'Paradox Interactive', 'Codemasters', 'SCi', 'Vivendi Games', 'Deep Silver', 'NovaLogic', 'Square Enix', 'Havas Interactive', 'id Software', 'Capcom', 'GT Interactive', 'Atari', 'Unknown', 'Sega', 'Swing! Entertainment', 'Bethesda Softworks', 'SquareSoft', 'Sony Computer Entertainment', 'Empire Interactive', 'Koch Media', 'NCSoft', 'Aspyr', 'Interplay', 'Midway Games', 'Zoo Digital Publishing', 'Popcorn Arcade', 'Hello Games', 'Valve Software', 'Valve', 'Introversion Software', 'Gathering of Developers', 'Tripwire Interactive', 'Virgin Interactive', 'Milestone S.r.l.', 'Maxis', 'Pinnacle', 'Square Enix ', 'LucasArts', 'Screenlife', 'DTP Entertainment', 'Funcom', 'Kalypso Media', 'inXile Entertainment', '2D Boy', 'Wargaming.net', 'Activision Blizzard'])
dict_keys(['11 bit studios', 'Activision Blizzard', 'Appirits', 'Aristocrat', 'ATARI', 'Bandai Namco', 'Blue Hat', 'Bushiroad', 'Capcom', 'CD Projekt', 'CI Games', 'COLOPL', 'Com2uS', 'Corsair Gaming', 'CyberAgent', 'DeNA', 'Digital Bros', 'DoubleDown Interactive', 'Drecom', 'Electronic Arts', 'Embracer Group', 'enish', 'Entain', 'Focus Home Interactive', 'Frontier Developments', 'GameStop', 'geechs', 'Gravity Co.', 'Gree', 'gumi', 'GungHo Online Entertainment', 'Huya', 'Keywords Studios', 'KLab', 'Koei Tecmo', 'Konami Holdings', 'Krafton', 'Marvelous', 'Microsoft', 'Mixi', 'Nacon', 'Nazara Technologies', 'NCsoft', 'Neowiz Games', 'NetEase', 'Netmarble', 'Nexon', 'Nexters', 'Nintendo', 'Paradox Interactive', 'Pearl Abyss', 'People Can Fly', 'Perfect World Entertainment', 'Playstudios', 'Playtech', 'Playtika', 'PlayWay', 'Razer', 'Roblox', 'Rovio Entertainment', 'SciPlay', 'Sea (Garena)', 'Sega Sammy Holdings', 'Skillz', 'Sony', 'Square Enix', 'Starbreeze', 'Super League Gaming', 'Take 2 Interactive', 'Team17', 'Ten Square Games', 'Tencent', 'The9', 'Ubisoft', 'Unity Software', 'Versus Systems', 'Webzen', 'Wemade', 'WonderPlanet', 'Valve'])

In [61]:
cid_gid = defaultdict(list)
registerGamectr = 0
for key1 in newGame_gid_company.keys():
    for key2 in cname_cid.keys():
        if key1 in key2 or key2 in key1:
            print('-'*20)
            print(key1)
            print(key2)
            print('-'*20)
            print(cname_cid[key2])
            print(newGame_gid_company[key1])
            cid_gid[cname_cid[key2]].extend(newGame_gid_company[key1])
            registerGamectr += len(newGame_gid_company[key1])
print(len(newGamedf.GID.unique()))
print(registerGamectr)
len(cid_gid)

--------------------
Activision
Activision Blizzard
--------------------
2
[1, 4, 45, 46, 47, 48, 49, 50, 51, 52, 84, 86, 87, 88, 134, 204, 213, 237, 258, 259, 261, 262, 263, 264, 329, 330, 331, 332, 333, 335]
--------------------
Microsoft Game Studios
Microsoft
--------------------
35
[8, 9, 10, 11, 13, 66, 120, 137, 138, 148, 161, 230, 231, 238, 267, 339]
--------------------
Ubisoft
Ubisoft
--------------------
70
[14, 15, 18, 19, 20, 21, 22, 23, 42, 94, 95, 105, 106, 107, 108, 208, 210, 211, 216, 217, 218, 223, 247, 248, 269, 273, 274, 278, 279, 280, 302, 303, 304, 305, 306, 307, 338]
--------------------
Electronic Arts
Electronic Arts
--------------------
19
[30, 31, 32, 33, 34, 43, 68, 69, 70, 76, 77, 78, 89, 90, 91, 136, 149, 154, 159, 161, 162, 163, 166, 167, 176, 188, 189, 190, 191, 192, 193, 195, 196, 251, 252, 256, 260, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297]
--------------------
Paradox Interactive
Paradox Interactive
--------------------
46
[54, 55, 139, 160, 207, 246]
--------------------
Square Enix
Square Enix
--------------------
62
[81, 83, 109, 110, 114, 115, 116, 141, 152, 153, 156, 158, 203, 232, 254, 326]
--------------------
Capcom
Capcom
--------------------
11
[92, 221, 222, 223, 224, 225, 226, 227, 228]
--------------------
Sega
Sega Sammy Holdings
--------------------
59
[100, 168, 194, 255, 271, 313, 314]
--------------------
Sony Computer Entertainment
Sony
--------------------
61
[112, 123]
--------------------
Valve Software
Valve
--------------------
79
[209]
--------------------
Valve
Valve
--------------------
79
[209]
--------------------
Square Enix
Square Enix
--------------------
62
[254]
--------------------
Activision Blizzard
Activision Blizzard
--------------------
2
[334]
339
181

10

In [62]:
# CompanyOwnsGame = pd,dataframe()
ctr = 0
for cid in cid_gid:
    for gid in cid_gid[cid]:
        if ctr == 0:
            CompanyOwnsGame = pd.DataFrame({'CID': cid, 'GID':gid}, index=[ctr])
        else:
            CompanyOwnsGame.loc[ctr] = [cid, gid]
        ctr += 1

CompanyOwnsGame = CompanyOwnsGame.set_index('CID')
CompanyOwnsGame

     GID
CID
2      1
2      4
2     45
2     46
2     47
..   ...
59   314
61   112
61   123
79   209
79   209

[181 rows x 1 columns]

In [63]:
CompanyOwnsGame.to_csv('clean/CompanyOwnGame.csv')

# CompanyOwnsPlatform

In [64]:
Platform

     PName   FoundDate
PID
1      3DS  2011-02-26
2       DS  2004-11-21
3      GBA  2001-03-21
4       GC  2001-09-14
5       PC  1971-01-01
6       PS  1994-12-03
7      PS2  2000-03-04
8      PS3  2006-11-11
9      PS4  2013-11-15
10     PSP  2004-12-12
11     PSV  2012-02-22
12   Steam  2003-09-12
13     Wii  2006-11-19
14    WiiU  2012-11-18
15    X360  2005-11-22
16      XB  2001-11-15
17    XOne  2013-11-22

In [65]:
company.CName.unique()

array(['11 bit studios', 'Activision Blizzard', 'Appirits', 'Aristocrat',
       'ATARI', 'Bandai Namco', 'Blue Hat', 'Bushiroad', 'Capcom',
       'CD Projekt', 'CI Games', 'COLOPL', 'Com2uS', 'Corsair Gaming',
       'CyberAgent', 'DeNA', 'Digital Bros', 'DoubleDown Interactive',
       'Drecom', 'Electronic Arts', 'Embracer Group', 'enish', 'Entain',
       'Focus Home Interactive', 'Frontier Developments', 'GameStop',
       'geechs', 'Gravity Co.', 'Gree', 'gumi',
       'GungHo Online Entertainment', 'Huya', 'Keywords Studios', 'KLab',
       'Koei Tecmo', 'Konami Holdings', 'Krafton', 'Marvelous',
       'Microsoft', 'Mixi', 'Nacon', 'Nazara Technologies', 'NCsoft',
       'Neowiz Games', 'NetEase', 'Netmarble', 'Nexon', 'Nexters',
       'Nintendo', 'Paradox Interactive', 'Pearl Abyss', 'People Can Fly',
       'Perfect World Entertainment', 'Playstudios', 'Playtech',
       'Playtika', 'PlayWay', 'Razer', 'Roblox', 'Rovio Entertainment',
       'SciPlay', 'Sea (Garena)', 'Sega Sammy Holdings', 'Skillz', 'Sony',
       'Square Enix', 'Starbreeze', 'Super League Gaming',
       'Take 2 Interactive', 'Team17', 'Ten Square Games', 'Tencent',
       'The9', 'Ubisoft', 'Unity Software', 'Versus Systems', 'Webzen',
       'Wemade', 'WonderPlanet', 'Valve'], dtype=object)

In [66]:
Platform = Platform.reset_index()

In [67]:
companyPlatform = defaultdict(list)
CPInfo = {'Nintendo':["3DS", "DS", "GBA", "GC", "Wii", "WiiU"], "Sony":["PS", "PS2", "PS3", "PS4", "PSP", "PSV"], "Microsoft":["PC", "X360", "XB", "XOne"], "Valve":["Steam"]}

for cname in CPInfo:
    cid = company.loc[company.CName == cname].CID.values[0]
    for pname in CPInfo[cname]:
        pid = Platform.loc[Platform.PName == pname].PID.values[0]
        companyPlatform[cid].append(pid)

In [68]:
companyPlatform

defaultdict(list,
            {45: [1, 2, 3, 4, 13, 14],
             61: [6, 7, 8, 9, 10, 11],
             35: [5, 15, 16, 17],
             79: [12]})

In [69]:
ctr = 0
for cid in companyPlatform:
    for pid in companyPlatform[cid]:
        if ctr == 0:
            CompanyOwnsPlatform = pd.DataFrame({'CID': cid, 'PID':pid}, index=[ctr])
        else:
            CompanyOwnsPlatform.loc[ctr] = [cid, pid]
        ctr += 1

CompanyOwnsPlatform = CompanyOwnsPlatform.set_index('CID')
CompanyOwnsPlatform

     PID
CID
45     1
45     2
45     3
45     4
45    13
45    14
61     6
61     7
61     8
61     9
61    10
61    11
35     5
35    15
35    16
35    17
79    12

In [70]:
CompanyOwnsPlatform.to_csv('clean/CompanyOwnsPlatform.csv')

In [71]:
company.CName.unique()

array(['11 bit studios', 'Activision Blizzard', 'Appirits', 'Aristocrat',
       'ATARI', 'Bandai Namco', 'Blue Hat', 'Bushiroad', 'Capcom',
       'CD Projekt', 'CI Games', 'COLOPL', 'Com2uS', 'Corsair Gaming',
       'CyberAgent', 'DeNA', 'Digital Bros', 'DoubleDown Interactive',
       'Drecom', 'Electronic Arts', 'Embracer Group', 'enish', 'Entain',
       'Focus Home Interactive', 'Frontier Developments', 'GameStop',
       'geechs', 'Gravity Co.', 'Gree', 'gumi',
       'GungHo Online Entertainment', 'Huya', 'Keywords Studios', 'KLab',
       'Koei Tecmo', 'Konami Holdings', 'Krafton', 'Marvelous',
       'Microsoft', 'Mixi', 'Nacon', 'Nazara Technologies', 'NCsoft',
       'Neowiz Games', 'NetEase', 'Netmarble', 'Nexon', 'Nexters',
       'Nintendo', 'Paradox Interactive', 'Pearl Abyss', 'People Can Fly',
       'Perfect World Entertainment', 'Playstudios', 'Playtech',
       'Playtika', 'PlayWay', 'Razer', 'Roblox', 'Rovio Entertainment',
       'SciPlay', 'Sea (Garena)', 'Sega Sammy Holdings', 'Skillz', 'Sony',
       'Square Enix', 'Starbreeze', 'Super League Gaming',
       'Take 2 Interactive', 'Team17', 'Ten Square Games', 'Tencent',
       'The9', 'Ubisoft', 'Unity Software', 'Versus Systems', 'Webzen',
       'Wemade', 'WonderPlanet', 'Valve'], dtype=object)

# Stock

In [96]:
ct = pd.read_csv('companyTicker.csv')
ct

           Company Name Stock Ticker
0        11 bit studios          11B
1   Activision Blizzard         ATVI
2              Appirits          NaN
3            Aristocrat          ALL
4                 ATARI        PONGF
..                  ...          ...
74       Unity Software            U
75       Versus Systems          NaN
76               Webzen          NaN
77               Wemade          NaN
78         WonderPlanet          NaN

[79 rows x 2 columns]

In [97]:
ct = ct.dropna(axis=0)
ct

                   Company Name Stock Ticker
0                11 bit studios          11B
1           Activision Blizzard         ATVI
3                    Aristocrat          ALL
4                         ATARI        PONGF
5                  Bandai Namco        NCBDF
8                        Capcom        CCOEY
9                    CD Projekt        OTGLF
11                       COLOPL       3668.T
12                       Com2uS    078340.KQ
14                   CyberAgent       4751.T
15                         DeNA        DNACF
16                 Digital Bros          AIM
19              Electronic Arts           EA
20               Embracer Group  EMBRAC-B.ST
22                       Entain        GMVHF
23       Focus Home Interactive     ALFOC.PA
24        Frontier Developments         FDEV
25                     GameStop          GME
27                  Gravity Co.         GRVY
30  GungHo Online Entertainment       3765.T
35              Konami Holdings        KNAMF
38                    Microsoft         MSFT
40                        Nacon     NACON.PA
44                      NetEase         NTES
46                        Nexon        NEXOF
48                     Nintendo        NTDOY
49          Paradox Interactive       PDX.ST
52  Perfect World Entertainment    002624.SZ
54                     Playtech           PT
58                       Roblox         RBLX
62          Sega Sammy Holdings        SGAMY
63                       Skillz         SKLZ
64                         Sony         SONY
65                  Square Enix        SQNXF
66                   Starbreeze    STAR-A.ST
68           Take 2 Interactive         TTWO
69                       Team17       TM17.L
71                      Tencent        TCEHY
73                      Ubisoft        UBSFY
74               Unity Software            U

In [98]:
import yfinance as yf

tickers = ct['Stock Ticker'].tolist()
tickers.remove('11B')
tickers

['ATVI',
 'ALL',
 'PONGF',
 'NCBDF',
 'CCOEY',
 'OTGLF',
 '3668.T',
 '078340.KQ',
 '4751.T',
 'DNACF',
 'AIM',
 'EA',
 'EMBRAC-B.ST',
 'GMVHF',
 'ALFOC.PA',
 'FDEV',
 'GME',
 'GRVY',
 '3765.T',
 'KNAMF',
 'MSFT',
 'NACON.PA',
 'NTES',
 'NEXOF',
 'NTDOY',
 'PDX.ST',
 '002624.SZ',
 'PT',
 'RBLX',
 'SGAMY',
 'SKLZ',
 'SONY',
 'SQNXF',
 'STAR-A.ST',
 'TTWO',
 'TM17.L',
 'TCEHY',
 'UBSFY',
 'U']

In [75]:
stocksdf = []
for t in tickers:
    stocksdf.append(yf.download(t, period="2y"))

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [76]:
for idx, ti in enumerate(tickers):
    stocksdf[idx]['Ticker'] = ti

In [77]:
stocks = pd.concat(stocksdf, axis=0, ignore_index=False)
stocks = stocks.sort_index()
stocks

,Open,High,Low,Close,Adj Close,Volume,Ticker
Date,,,,,,,
2020-12-07,1710.000000,1755.000000,1705.000000,1705.000000,1677.941895,2498400,4751.T
2020-12-07,248.199997,251.600006,246.399994,250.800003,248.125992,60098,PDX.ST
2020-12-07,84.500000,85.925003,84.150002,85.925003,85.925003,2958178,EMBRAC-B.ST
2020-12-07,28.900000,28.950001,28.139999,28.350000,25.825859,19044727,002624.SZ
2020-12-07,1.050000,1.055000,1.040000,1.050000,1.050000,60897,STAR-A.ST
...,...,...,...,...,...,...,...
2022-12-07,24.280001,24.280001,24.259600,24.260000,24.260000,1235,FDEV
2022-12-07,79.139999,79.394997,78.669998,79.040001,79.040001,478895,SONY
2022-12-07,23.400000,23.610001,21.969999,22.260000,22.260000,9050886,GME
2022-12-07,0.880900,0.900000,0.850000,0.856600,0.856600,8073518,SKLZ
2022-12-07,34.020000,35.219898,32.799999,33.770000,33.770000,10987650,U

## CompanyHasStock Relation Table

In [99]:
ct = ct.drop([0]).reset_index()
ct

    index                 Company Name Stock Ticker
0       1          Activision Blizzard         ATVI
1       3                   Aristocrat          ALL
2       4                        ATARI        PONGF
3       5                 Bandai Namco        NCBDF
4       8                       Capcom        CCOEY
5       9                   CD Projekt        OTGLF
6      11                       COLOPL       3668.T
7      12                       Com2uS    078340.KQ
8      14                   CyberAgent       4751.T
9      15                         DeNA        DNACF
10     16                 Digital Bros          AIM
11     19              Electronic Arts           EA
12     20               Embracer Group  EMBRAC-B.ST
13     22                       Entain        GMVHF
14     23       Focus Home Interactive     ALFOC.PA
15     24        Frontier Developments         FDEV
16     25                     GameStop          GME
17     27                  Gravity Co.         GRVY
18     30  GungHo Online Entertainment       3765.T
19     35              Konami Holdings        KNAMF
20     38                    Microsoft         MSFT
21     40                        Nacon     NACON.PA
22     44                      NetEase         NTES
23     46                        Nexon        NEXOF
24     48                     Nintendo        NTDOY
25     49          Paradox Interactive       PDX.ST
26     52  Perfect World Entertainment    002624.SZ
27     54                     Playtech           PT
28     58                       Roblox         RBLX
29     62          Sega Sammy Holdings        SGAMY
30     63                       Skillz         SKLZ
31     64                         Sony         SONY
32     65                  Square Enix        SQNXF
33     66                   Starbreeze    STAR-A.ST
34     68           Take 2 Interactive         TTWO
35     69                       Team17       TM17.L
36     71                      Tencent        TCEHY
37     73                      Ubisoft        UBSFY
38     74               Unity Software            U

In [100]:
ct = ct.drop(columns=['index'])

In [101]:
ct

                   Company Name Stock Ticker
0           Activision Blizzard         ATVI
1                    Aristocrat          ALL
2                         ATARI        PONGF
3                  Bandai Namco        NCBDF
4                        Capcom        CCOEY
5                    CD Projekt        OTGLF
6                        COLOPL       3668.T
7                        Com2uS    078340.KQ
8                    CyberAgent       4751.T
9                          DeNA        DNACF
10                 Digital Bros          AIM
11              Electronic Arts           EA
12               Embracer Group  EMBRAC-B.ST
13                       Entain        GMVHF
14       Focus Home Interactive     ALFOC.PA
15        Frontier Developments         FDEV
16                     GameStop          GME
17                  Gravity Co.         GRVY
18  GungHo Online Entertainment       3765.T
19              Konami Holdings        KNAMF
20                    Microsoft         MSFT
21                        Nacon     NACON.PA
22                      NetEase         NTES
23                        Nexon        NEXOF
24                     Nintendo        NTDOY
25          Paradox Interactive       PDX.ST
26  Perfect World Entertainment    002624.SZ
27                     Playtech           PT
28                       Roblox         RBLX
29          Sega Sammy Holdings        SGAMY
30                       Skillz         SKLZ
31                         Sony         SONY
32                  Square Enix        SQNXF
33                   Starbreeze    STAR-A.ST
34           Take 2 Interactive         TTWO
35                       Team17       TM17.L
36                      Tencent        TCEHY
37                      Ubisoft        UBSFY
38               Unity Software            U

In [102]:
ct = ct.rename(columns={'Company Name':'CID','Stock Ticker':'Ticker'})
ct

                            CID       Ticker
0           Activision Blizzard         ATVI
1                    Aristocrat          ALL
2                         ATARI        PONGF
3                  Bandai Namco        NCBDF
4                        Capcom        CCOEY
5                    CD Projekt        OTGLF
6                        COLOPL       3668.T
7                        Com2uS    078340.KQ
8                    CyberAgent       4751.T
9                          DeNA        DNACF
10                 Digital Bros          AIM
11              Electronic Arts           EA
12               Embracer Group  EMBRAC-B.ST
13                       Entain        GMVHF
14       Focus Home Interactive     ALFOC.PA
15        Frontier Developments         FDEV
16                     GameStop          GME
17                  Gravity Co.         GRVY
18  GungHo Online Entertainment       3765.T
19              Konami Holdings        KNAMF
20                    Microsoft         MSFT
21                        Nacon     NACON.PA
22                      NetEase         NTES
23                        Nexon        NEXOF
24                     Nintendo        NTDOY
25          Paradox Interactive       PDX.ST
26  Perfect World Entertainment    002624.SZ
27                     Playtech           PT
28                       Roblox         RBLX
29          Sega Sammy Holdings        SGAMY
30                       Skillz         SKLZ
31                         Sony         SONY
32                  Square Enix        SQNXF
33                   Starbreeze    STAR-A.ST
34           Take 2 Interactive         TTWO
35                       Team17       TM17.L
36                      Tencent        TCEHY
37                      Ubisoft        UBSFY
38               Unity Software            U

In [107]:
company[company.CName=='Activision Blizzard'].CID.item()

2

In [108]:
for idx, row in ct.iterrows():
    CName = row.CID
    cid = company[company.CName==CName].CID.item()
    ct.loc[idx, 'CID'] = cid

ct

   CID       Ticker
0    2         ATVI
1    4          ALL
2    1        PONGF
3    5        NCBDF
4   11        CCOEY
5    8        OTGLF
6   10       3668.T
7   12    078340.KQ
8   14       4751.T
9   15        DNACF
10  16          AIM
11  19           EA
12  20  EMBRAC-B.ST
13  21        GMVHF
14  22     ALFOC.PA
15  23         FDEV
16  24          GME
17  25         GRVY
18  27       3765.T
19  32        KNAMF
20  35         MSFT
21  38     NACON.PA
22  41         NTES
23  43        NEXOF
24  45        NTDOY
25  46       PDX.ST
26  49    002624.SZ
27  52           PT
28  55         RBLX
29  59        SGAMY
30  60         SKLZ
31  61         SONY
32  62        SQNXF
33  63    STAR-A.ST
34  65         TTWO
35  66       TM17.L
36  68        TCEHY
37  70        UBSFY
38  71            U

In [110]:
ct.to_csv('clean/CompanyHasStock.csv', index=False, quoting=csv.QUOTE_NONE)

## TimeTickerPrice Relation Table

In [78]:
TimeTickerPrice = stocks[['Ticker', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume']]
TimeTickerPrice

,Ticker,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,,
2020-12-07,4751.T,1710.000000,1755.000000,1705.000000,1705.000000,1677.941895,2498400
2020-12-07,PDX.ST,248.199997,251.600006,246.399994,250.800003,248.125992,60098
2020-12-07,EMBRAC-B.ST,84.500000,85.925003,84.150002,85.925003,85.925003,2958178
2020-12-07,002624.SZ,28.900000,28.950001,28.139999,28.350000,25.825859,19044727
2020-12-07,STAR-A.ST,1.050000,1.055000,1.040000,1.050000,1.050000,60897
...,...,...,...,...,...,...,...
2022-12-07,FDEV,24.280001,24.280001,24.259600,24.260000,24.260000,1235
2022-12-07,SONY,79.139999,79.394997,78.669998,79.040001,79.040001,478895
2022-12-07,GME,23.400000,23.610001,21.969999,22.260000,22.260000,9050886
2022-12-07,SKLZ,0.880900,0.900000,0.850000,0.856600,0.856600,8073518
2022-12-07,U,34.020000,35.219898,32.799999,33.770000,33.770000,10987650

In [80]:
TimeTickerPrice = TimeTickerPrice.rename(columns={'Adj Close': 'Adj_Close'})
TimeTickerPrice

,Ticker,Open,High,Low,Close,Adj_Close,Volume
Date,,,,,,,
2020-12-07,4751.T,1710.000000,1755.000000,1705.000000,1705.000000,1677.941895,2498400
2020-12-07,PDX.ST,248.199997,251.600006,246.399994,250.800003,248.125992,60098
2020-12-07,EMBRAC-B.ST,84.500000,85.925003,84.150002,85.925003,85.925003,2958178
2020-12-07,002624.SZ,28.900000,28.950001,28.139999,28.350000,25.825859,19044727
2020-12-07,STAR-A.ST,1.050000,1.055000,1.040000,1.050000,1.050000,60897
...,...,...,...,...,...,...,...
2022-12-07,FDEV,24.280001,24.280001,24.259600,24.260000,24.260000,1235
2022-12-07,SONY,79.139999,79.394997,78.669998,79.040001,79.040001,478895
2022-12-07,GME,23.400000,23.610001,21.969999,22.260000,22.260000,9050886
2022-12-07,SKLZ,0.880900,0.900000,0.850000,0.856600,0.856600,8073518
2022-12-07,U,34.020000,35.219898,32.799999,33.770000,33.770000,10987650

In [81]:
TimeTickerPrice.to_csv('clean/TimeTickerPrice.csv', quoting=csv.QUOTE_NONE)

## Stock Table

In [148]:
tickers_yf = [yf.Ticker(x) for x in tickers]
tickers_yf[0].info.keys()

dict_keys(['zip', 'sector', 'fullTimeEmployees', 'longBusinessSummary', 'city', 'phone', 'state', 'country', 'companyOfficers', 'website', 'maxAge', 'address1', 'industry', 'ebitdaMargins', 'profitMargins', 'grossMargins', 'operatingCashflow', 'revenueGrowth', 'operatingMargins', 'ebitda', 'targetLowPrice', 'recommendationKey', 'grossProfits', 'freeCashflow', 'targetMedianPrice', 'currentPrice', 'earningsGrowth', 'currentRatio', 'returnOnAssets', 'numberOfAnalystOpinions', 'targetMeanPrice', 'debtToEquity', 'returnOnEquity', 'targetHighPrice', 'totalCash', 'totalDebt', 'totalRevenue', 'totalCashPerShare', 'financialCurrency', 'revenuePerShare', 'quickRatio', 'recommendationMean', 'exchange', 'shortName', 'longName', 'exchangeTimezoneName', 'exchangeTimezoneShortName', 'isEsgPopulated', 'gmtOffSetMilliseconds', 'quoteType', 'symbol', 'messageBoardId', 'market', 'annualHoldingsTurnover', 'enterpriseToRevenue', 'beta3Year', 'enterpriseToEbitda', '52WeekChange', 'morningStarRiskRating', 'forwardEps', 'revenueQuarterlyGrowth', 'sharesOutstanding', 'fundInceptionDate', 'annualReportExpenseRatio', 'totalAssets', 'bookValue', 'sharesShort', 'sharesPercentSharesOut', 'fundFamily', 'lastFiscalYearEnd', 'heldPercentInstitutions', 'netIncomeToCommon', 'trailingEps', 'lastDividendValue', 'SandP52WeekChange', 'priceToBook', 'heldPercentInsiders', 'nextFiscalYearEnd', 'yield', 'mostRecentQuarter', 'shortRatio', 'sharesShortPreviousMonthDate', 'floatShares', 'beta', 'enterpriseValue', 'priceHint', 'threeYearAverageReturn', 'lastSplitDate', 'lastSplitFactor', 'legalType', 'lastDividendDate', 'morningStarOverallRating', 'earningsQuarterlyGrowth', 'priceToSalesTrailing12Months', 'dateShortInterest', 'pegRatio', 'ytdReturn', 'forwardPE', 'lastCapGain', 'shortPercentOfFloat', 'sharesShortPriorMonth', 'impliedSharesOutstanding', 'category', 'fiveYearAverageReturn', 'previousClose', 'regularMarketOpen', 'twoHundredDayAverage', 'trailingAnnualDividendYield', 'payoutRatio', 'volume24Hr', 'regularMarketDayHigh', 'navPrice', 'averageDailyVolume10Day', 'regularMarketPreviousClose', 'fiftyDayAverage', 'trailingAnnualDividendRate', 'open', 'toCurrency', 'averageVolume10days', 'expireDate', 'algorithm', 'dividendRate', 'exDividendDate', 'circulatingSupply', 'startDate', 'regularMarketDayLow', 'currency', 'trailingPE', 'regularMarketVolume', 'lastMarket', 'maxSupply', 'openInterest', 'marketCap', 'volumeAllCurrencies', 'strikePrice', 'averageVolume', 'dayLow', 'ask', 'askSize', 'volume', 'fiftyTwoWeekHigh', 'fromCurrency', 'fiveYearAvgDividendYield', 'fiftyTwoWeekLow', 'bid', 'tradeable', 'dividendYield', 'bidSize', 'dayHigh', 'coinMarketCapLink', 'regularMarketPrice', 'preMarketPrice', 'logo_url', 'trailingPegRatio'])

In [152]:
stockinfo = defaultdict(list)
for idx, tk in enumerate(tickers):
    try:
        stockinfo[tk].extend([tickers_yf[idx].info['country'], tickers_yf[idx].info['exchange'], tickers_yf[idx].info['fiftyTwoWeekHigh'], tickers_yf[idx].info['fiftyTwoWeekLow'], tickers_yf[idx].info['market']])
    except:
        pass

In [163]:
i = 0
for ticker, info in stockinfo.items():
    if i == 0:
        c, e, h, l, m = info
        stockdf = pd.DataFrame({'Ticker': ticker, 'Country':c, 'Exchange':e, 'FiftyTwoWeekHigh':h, 'FiftyTwoWeekLow':l, 'Market':m}, index=[i])
    else:
        if info:
            res = [ticker]
            res.extend(info)
            stockdf.loc[i,:] = res
    i += 1

stockdf

,Ticker,Country,Exchange,FiftyTwoWeekHigh,FiftyTwoWeekLow,Market
0,ATVI,United States,NMS,86.9000,57.470,us_market
1,ALL,United States,NYQ,144.4600,106.110,us_market
2,PONGF,France,PNK,0.5000,0.100,us_market
3,NCBDF,Japan,PNK,80.5700,63.000,us_market
4,CCOEY,Japan,PNK,16.1600,10.600,us_market
5,OTGLF,Poland,PNK,50.0000,13.050,us_market
6,3668.T,Japan,JPX,753.0000,592.000,jp_market
7,078340.KQ,South Korea,KOE,150200.0000,61100.000,kr_market
8,4751.T,Japan,JPX,2065.0000,1068.000,jp_market
9,DNACF,Japan,PNK,15.8400,12.850,us_market
10,AIM,United States,ASE,1.4300,0.370,us_market
11,EA,United States,NMS,142.7900,109.240,us_market
12,EMBRAC-B.ST,Sweden,STO,101.0000,41.000,se_market
13,GMVHF,United Kingdom,PNK,23.8200,11.700,us_market
14,ALFOC.PA,France,PAR,50.4000,37.050,fr_market
16,GME,United States,NYQ,49.8525,19.395,us_market
17,GRVY,South Korea,NGM,79.8400,40.150,us_market
18,3765.T,Japan,JPX,3030.0000,2027.000,jp_market
19,KNAMF,Japan,PNK,64.8500,40.770,us_market
20,MSFT,United States,NMS,344.3000,213.430,us_market
21,NACON.PA,France,PAR,6.3000,2.015,fr_market
22,NTES,China,NMS,108.7700,53.090,us_market
23,NEXOF,Japan,PNK,23.9500,16.330,us_market
24,NTDOY,Japan,PNK,13.6500,9.760,us_market
25,PDX.ST,Sweden,STO,210.0000,151.000,se_market
26,002624.SZ,China,SHZ,23.6700,11.000,cn_market
27,PT,China,NGM,7.1000,0.250,us_market
28,RBLX,United States,NYQ,125.9900,21.650,us_market
29,SGAMY,Japan,PNK,4.7900,3.050,us_market
30,SKLZ,United States,NYQ,10.1700,0.831,us_market
31,SONY,Japan,NYQ,133.7500,61.720,us_market
32,SQNXF,Japan,PNK,55.5000,38.420,us_market
33,STAR-A.ST,Sweden,STO,1.3100,0.840,se_market
34,TTWO,United States,NMS,182.2500,90.000,us_market
35,TM17.L,United Kingdom,LSE,820.0000,335.000,gb_market
36,TCEHY,China,PNK,63.0000,24.750,us_market
37,UBSFY,France,PNK,12.2900,4.750,us_market
38,U,United States,NYQ,157.4800,21.220,us_market

In [164]:
stockdf.to_csv('clean/stock.csv', index=False)